"""
Cross-store asset list export in the GUCCI_资产表 format.

Produces a single-sheet xlsx with the 17 columns defined in
``inspections.constants.ASSET_LIST_COLUMNS`` (STORE, JDA, Asset ID, Category,
Brand-Model, SN, Warranty-start, Usage, Status, Comment, IP Address, CPU,
Memory, HDD, Windows&IOS Version, Drive C Free Space, Intact Asset Tag).

Row values are built by reusing ``report_generator._asset_list_value_map``, which
already applies the Kering business rules (effective_status -> "Not In Store" for
untouched expected devices, monitor-size comment markers, intact-tag autofill,
merged Windows/iOS version, xstore peripheral linking).

Used by the web UI's "Export Asset List" view; complements (does not replace) the
per-store report workbook generated by ``generate_inspection_report``.
"""
import io
import re
from datetime import date

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from inspections.constants import ASSET_LIST_COLUMNS
from inspections.models import InspectionDevice
from inspections.services.report_generator import _asset_list_value_map
from inspections.services import transforms

_HEADER_FONT = Font(bold=True, size=11, color='FFFFFF')
_HEADER_FILL = PatternFill('solid', fgColor='4F6228')
_WRAP = Alignment(vertical='top', wrap_text=True)

# Column widths tuned to match the reference GUCCI_资产表_2026 W5.xlsx.
_COLUMN_WIDTHS = {
    'STORE': 14, 'JDA': 10, 'Asset ID': 20, 'Category': 14, 'Brand-Model': 26,
    'SN': 24, 'Warranty-start': 14, 'Usage': 14, 'Status': 12, 'Comment': 30,
    'IP Address': 16, 'CPU': 18, 'Memory': 14, 'HDD': 14,
    'Windows&IOS Version': 22, 'Drive C Free Space': 16, 'Intact Asset Tag': 14,
}
_TEXT_COLUMNS = {'Asset ID', 'SN', 'JDA'}


def _safe_filename(text):
    """Strip characters that are illegal in Windows/Unix filenames."""
    cleaned = re.sub(r'[<>:"/\\|?*\x00-\x1f]', '_', str(text or '')).strip()
    return cleaned or 'asset_list'


def _iso_week_of(d):
    """Return (iso_year, iso_week) for a date."""
    iso = d.isocalendar()
    return iso[0], iso[1]


def _derive_filename(inspections, batch=None):
    """Pick a sensible default filename for the export.

    Priority:
    1. Single division + single ISO week -> ``<BRAND>_资产表_<YEAR> W<WEEK>.xlsx``
       (matches the reference ``GUCCI_资产表_2026 W5.xlsx``).
    2. Batch provided -> ``<BatchName>.xlsx``.
    3. Fallback -> ``asset_list_<YYYYMMDD>.xlsx``.
    """
    inspections = list(inspections)
    if not inspections:
        return f'asset_list_{date.today().strftime("%Y%m%d")}.xlsx'

    divisions = {i.division_id for i in inspections if i.division_id}
    division_names = {i.division.name for i in inspections if i.division}
    weeks = {_iso_week_of(i.inspection_date) for i in inspections if i.inspection_date}

    if len(divisions) == 1 and len(weeks) == 1 and division_names:
        brand = next(iter(division_names))
        iso_year, iso_week = next(iter(weeks))
        return f'{_safe_filename(brand)}_资产表_{iso_year} W{iso_week}.xlsx'

    if batch is not None:
        return f'{_safe_filename(batch.name)}.xlsx'

    return f'asset_list_{date.today().strftime("%Y%m%d")}.xlsx'


def build_asset_list_workbook(inspections):
    """Return an in-memory ``Workbook`` with one asset_list sheet.

    Devices are ordered by inspection date, then JDA code, then row_order so the
    output reads naturally top-to-bottom across stores.
    """
    inspection_ids = [i.id for i in inspections]
    devices = (
        InspectionDevice.objects
        .filter(store_inspection_id__in=inspection_ids)
        .select_related('store_inspection', 'asset')
        .order_by(
            'store_inspection__inspection_date',
            'store_inspection__jda_code',
            'row_order',
            'created_at',
        )
    )

    # Apply xstore peripheral linking per inspection so host PC Asset IDs are
    # attached to xstore-N peripherals (same transform the per-store report uses).
    devices_by_inspection = {}
    for device in devices:
        devices_by_inspection.setdefault(device.store_inspection_id, []).append(device)
    for inspection_id, group in devices_by_inspection.items():
        transforms.link_xstore_peripherals(group)

    workbook = Workbook()
    sheet = workbook.active
    sheet.title = 'asset_list'

    # Header row.
    for col_index, name in enumerate(ASSET_LIST_COLUMNS, start=1):
        cell = sheet.cell(row=1, column=col_index, value=name)
        cell.font = _HEADER_FONT
        cell.fill = _HEADER_FILL
        cell.alignment = _WRAP
        width = _COLUMN_WIDTHS.get(name)
        if width:
            sheet.column_dimensions[get_column_letter(col_index)].width = width

    # Freeze the header row for scrolling.
    sheet.freeze_panes = 'A2'

    # Data rows: iterate in the same order the queryset yields, but use the
    # per-inspection grouped lists so the xstore linking transform is visible.
    row_index = 2
    ordered_inspections = sorted(
        inspections,
        key=lambda i: (i.inspection_date or date.max, i.jda_code or '', i.store_name or ''),
    )
    text_col_indexes = {
        ASSET_LIST_COLUMNS.index(name) + 1
        for name in _TEXT_COLUMNS if name in ASSET_LIST_COLUMNS
    }
    for inspection in ordered_inspections:
        for device in devices_by_inspection.get(inspection.id, []):
            values = _asset_list_value_map(inspection, device)
            for col_index, name in enumerate(ASSET_LIST_COLUMNS, start=1):
                cell = sheet.cell(row=row_index, column=col_index, value=values.get(name, ''))
                cell.alignment = _WRAP
                if col_index in text_col_indexes:
                    cell.number_format = '@'  # keep long identifiers as text
            row_index += 1

    return workbook


def export_asset_list(inspections, *, filename=None, batch=None):
    """Build the asset-list workbook and return ``(content_bytes, filename)``.

    Args:
        inspections: iterable of ``StoreInspection``. May be a queryset; it will
            be materialized to a list so the filename derivation can inspect it.
        filename: override the auto-derived filename.
        batch: optional ``InspectionBatch`` used for filename derivation when the
            inspections span multiple divisions or weeks.

    Returns:
        ``(bytes, str)`` — the xlsx content and the filename to serve it as.
    """
    inspections = list(inspections)
    workbook = build_asset_list_workbook(inspections)

    buffer = io.BytesIO()
    workbook.save(buffer)
    content = buffer.getvalue()

    if not filename:
        filename = _derive_filename(inspections, batch=batch)
    if not filename.lower().endswith('.xlsx'):
        filename = f'{filename}.xlsx'

    return content, filename
