# Generated by Django 5.2.8 on 2026-04-16 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyOrderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=30, unique=True)),
                ('sharepoint_file', models.FileField(upload_to='invoices/sharepoint/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_rows', models.PositiveIntegerField(default=0)),
                ('failed_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_weekly_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('invoice_date', models.DateField()),
                ('kering_group_po_number', models.CharField(max_length=100)),
                ('internal_order', models.CharField(max_length=100)),
                ('sap_cost_center', models.CharField(max_length=100)),
                ('source_row_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekly_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_infos', to='invoices.weeklyorderbatch')),
            ],
            options={
                'ordering': ['invoice_date', 'source_row_number', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='weeklyorderbatch',
            index=models.Index(fields=['batch_id'], name='invoices_we_batch_i_fbe56c_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyorderbatch',
            index=models.Index(fields=['status'], name='invoices_we_status_f18de0_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyorderbatch',
            index=models.Index(fields=['uploaded_at'], name='invoices_we_uploade_f51155_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceinfo',
            index=models.Index(fields=['invoice_number'], name='invoices_in_invoice_e60afe_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceinfo',
            index=models.Index(fields=['invoice_date'], name='invoices_in_invoice_d20a18_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceinfo',
            index=models.Index(fields=['kering_group_po_number'], name='invoices_in_kering__af6cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceinfo',
            index=models.Index(fields=['internal_order'], name='invoices_in_interna_0f03ce_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceinfo',
            index=models.Index(fields=['sap_cost_center'], name='invoices_in_sap_cos_154ad8_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoiceinfo',
            constraint=models.UniqueConstraint(fields=('kering_group_po_number', 'internal_order', 'sap_cost_center'), name='uniq_invoice_business_keys'),
        ),
    ]
