# Generated by Django 5.2.8 on 2026-04-16 04:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('invoices', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceInfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5)),
            ],
            options={
                'ordering': ['line_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='bill_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='delivery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_infos', to='deliveries.deliveryorder'),
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_infos', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddIndex(
            model_name='invoiceinfo',
            index=models.Index(fields=['bill_to'], name='invoices_in_bill_to_fde398_idx'),
        ),
        migrations.AddField(
            model_name='invoiceinfoitem',
            name='invoice_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoiceinfo'),
        ),
        migrations.AddIndex(
            model_name='invoiceinfoitem',
            index=models.Index(fields=['invoice_info', 'line_number'], name='invoices_in_invoice_51dfb4_idx'),
        ),
    ]
