# Generated by Django 5.2.8 on 2026-04-16 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('invoices', '0002_invoiceinfoitem_invoiceinfo_bill_to_and_more'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('sent_to', models.TextField(help_text='Comma separated recipients')),
                ('cc', models.TextField(blank=True, help_text='Comma separated CC recipients')),
                ('bcc', models.TextField(blank=True, help_text='Comma separated BCC recipients')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('client_confirmed', 'Client Confirmed'), ('esker_forwarded', 'Esker Forwarded'), ('failed', 'Failed')], default='draft', max_length=30)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('esker_sent', models.BooleanField(default=False)),
                ('esker_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_dispatches', to=settings.AUTH_USER_MODEL)),
                ('delivery_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_dispatches', to='deliveries.deliveryorder')),
                ('invoice_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_dispatches', to='invoices.invoiceinfo')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_dispatches', to='quotations.quotation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['quotation', 'status'], name='invoices_em_quotati_e1fdc6_idx'), models.Index(fields=['sent_at'], name='invoices_em_sent_at_ed5ed1_idx'), models.Index(fields=['esker_sent'], name='invoices_em_esker_s_8c65fe_idx')],
            },
        ),
    ]
