# Generated by Django 5.2.8 on 2026-04-24 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_receivedemailmessage_rfq_confidence_and_more'),
        ('deliveries', '0001_initial'),
        ('invoices', '0004_workflowstatusaudit'),
        ('quotations', '0005_quotation_requires_confirmation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildispatch',
            name='reply_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emaildispatch',
            name='reply_references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emaildispatch',
            name='source_email_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_dispatches', to='accounts.receivedemailmessage'),
        ),
        migrations.AddIndex(
            model_name='emaildispatch',
            index=models.Index(fields=['source_email_message', 'status'], name='invoices_em_source__bfcc6f_idx'),
        ),
    ]
