"""
Django settings for hengjiams project.

HengJi Asset Management System (AMS) - A comprehensive SaaS solution
for managing company assets with multi-language support, 2FA, and audit capabilities.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f(g_zcqk%xwx=g3#lnyp=@$c+r%cj=aw8xpr(*=4wc=iwq+!i4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

MINIMAX_TOKEN_PLAN_KEY = os.environ.get('minimax_token_plan_key', '')
MINIMAX_RFQ_API_URL = os.environ.get('MINIMAX_RFQ_API_URL', 'https://api.minimaxi.com/anthropic/v1/messages')
MINIMAX_RFQ_MODEL = os.environ.get('MINIMAX_RFQ_MODEL', 'MiniMax-M2.7-highspeed')
MINIMAX_RFQ_TIMEOUT_SECONDS = float(os.environ.get('MINIMAX_RFQ_TIMEOUT_SECONDS', '30'))
MINIMAX_RFQ_MAX_TOKENS = int(os.environ.get('MINIMAX_RFQ_MAX_TOKENS', '800'))
TEST_OUTBOUND_EMAIL_OVERRIDE = os.environ.get('TEST_OUTBOUND_EMAIL_OVERRIDE', 'sean.liu@istore-tech.com').strip()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'django_extensions',  # Provides useful extensions for Django development
    'django_otp',  # Two-factor authentication support
    'django_otp.plugins.otp_totp',  # TOTP (Time-based OTP) support
    'django_otp.plugins.otp_static',  # Static OTP tokens for backup
    'rest_framework',  # REST API framework
    # Local apps
    'accounts',  # Custom user management with roles and 2FA
    'assets',  # Asset management core functionality
    'companies',  # Company and division management
    'audit',  # Asset audit and tracking system
    'reports',  # Reporting and analytics
    'dashboard',  # Main dashboard and overview
    'users',  # User management
    'api',  # REST API
    'mobile',  # Mobile interface
    'products',  # Product price list
    'customers',  # Customer profiles
    'quotations',  # Quotation management
    'purchases',  # Purchase and stock management
    'deliveries',  # Delivery order management
    'invoices',  # Weekly sharepoint processing and invoice staging
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # For internationalization
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',  # For 2FA support
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hengjiams.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # For internationalization
                'dashboard.context_processors.pending_tasks',
            ],
        },
    },
]

WSGI_APPLICATION = 'hengjiams.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite for development (will switch to PostgreSQL later)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# PostgreSQL configuration for production (commented out for now)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'hengjiams_db',
#         'USER': 'hengjiams_django',
#         'PASSWORD': 'hengjiams_djangopass',
#         'HOST': '127.0.0.1',
#         'PORT': '5433',
#         'OPTIONS': {
#             'charset': 'utf8',
#         },
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# List of supported languages
LANGUAGES = [
    ('en-us', 'English (US)'),
    ('zh-cn', 'Simplified Chinese'),
]

# Directory containing translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
AUTH_USER_MODEL = 'accounts.User'  # Custom user model

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Two-Factor Authentication settings
OTP_TOTP_ISSUER = 'HengJi AMS'
OTP_LOGIN_URL = '/login/'

# Session settings
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Security settings for production
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Asset management specific settings
ASSET_PHOTO_UPLOAD_PATH = 'assets/photos/'
ASSET_BARCODE_UPLOAD_PATH = 'assets/barcodes/'
MAX_UPLOAD_SIZE = 5242880  # 5MB

# Email settings (for notifications)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'hengjiams.log',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'assets': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
