"""
Django settings for hengjiams project.

HengJi Asset Management System (AMS) - A comprehensive SaaS solution
for managing company assets with multi-language support, 2FA, and audit capabilities.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


def _env_bool(name, default):
    """Parse a boolean environment variable (accepts 1/true/yes/on)."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: keep the secret key used in production secret!
# Production MUST set DJANGO_SECRET_KEY (environment or repo-local .env).
# The fallback below is an insecure development-only key.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-f(g_zcqk%xwx=g3#lnyp=@$c+r%cj=aw8xpr(*=4wc=iwq+!i4',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True for local development; production MUST set DJANGO_DEBUG=False.
DEBUG = _env_bool('DJANGO_DEBUG', True)

# Comma-separated host list; defaults to '*' for development convenience.
# Production MUST set DJANGO_ALLOWED_HOSTS to the real domain(s).
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')
    if host.strip()
]

# Fail fast rather than ship an insecure production configuration:
# when DEBUG is off, the development fallback secret key is not acceptable.
if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be set to a strong, non-insecure value when '
        'DJANGO_DEBUG is False.'
    )

MINIMAX_TOKEN_PLAN_KEY = os.environ.get('minimax_token_plan_key', '')
MINIMAX_RFQ_API_URL = os.environ.get('MINIMAX_RFQ_API_URL', 'https://api.minimaxi.com/anthropic/v1/messages')
MINIMAX_RFQ_MODEL = os.environ.get('MINIMAX_RFQ_MODEL', 'MiniMax-M2.7-highspeed')
MINIMAX_RFQ_TIMEOUT_SECONDS = float(os.environ.get('MINIMAX_RFQ_TIMEOUT_SECONDS', '30'))
MINIMAX_RFQ_MAX_TOKENS = int(os.environ.get('MINIMAX_RFQ_MAX_TOKENS', '800'))
TEST_OUTBOUND_EMAIL_OVERRIDE = os.environ.get('TEST_OUTBOUND_EMAIL_OVERRIDE', 'sean.liu@istore-tech.com').strip()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'django_extensions',  # Provides useful extensions for Django development
    'django_otp',  # Two-factor authentication support
    'django_otp.plugins.otp_totp',  # TOTP (Time-based OTP) support
    'django_otp.plugins.otp_static',  # Static OTP tokens for backup
    'rest_framework',  # REST API framework
    # Local apps
    'accounts',  # Custom user management with roles and 2FA
    'assets',  # Asset management core functionality
    'companies',  # Company and division management
    'audit',  # Asset audit and tracking system
    'reports',  # Reporting and analytics
    'dashboard',  # Main dashboard and overview
    'users',  # User management
    'api',  # REST API
    'mobile',  # Mobile interface
    'products',  # Product price list
    'customers',  # Customer profiles
    'quotations',  # Quotation management
    'purchases',  # Purchase and stock management
    'deliveries',  # Delivery order management
    'invoices',  # Weekly sharepoint processing and invoice staging
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # For internationalization
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',  # For 2FA support
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# WhiteNoise serves static files in production. It must sit directly after
# SecurityMiddleware. Guarded by DEBUG so local development does not require
# the package to be installed (dev uses runserver's own static handling).
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'hengjiams.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # For internationalization
                'dashboard.context_processors.pending_tasks',
            ],
        },
    },
]

WSGI_APPLICATION = 'hengjiams.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Defaults to SQLite for local development. For PostgreSQL (production), set
# these in the environment or repo-local .env:
#   DATABASE_ENGINE=django.db.backends.postgresql
#   DATABASE_NAME=hengjiams_db
#   DATABASE_USER=hengjiams_django
#   DATABASE_PASSWORD=<secret>
#   DATABASE_HOST=127.0.0.1
#   DATABASE_PORT=5432
# SQLite ignores USER/PASSWORD/HOST/PORT, so the empty defaults are safe.
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DATABASE_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.environ.get('DATABASE_NAME', str(BASE_DIR / 'db.sqlite3')),
        'USER': os.environ.get('DATABASE_USER', ''),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', ''),
        'HOST': os.environ.get('DATABASE_HOST', ''),
        'PORT': os.environ.get('DATABASE_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# List of supported languages
LANGUAGES = [
    ('en-us', 'English (US)'),
    ('zh-cn', 'Simplified Chinese'),
]

# Directory containing translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Static files storage (Django 5.x STORAGES API).
# Production: WhiteNoise's CompressedManifestStaticFilesStorage - hashed
#   filenames for cache-busting plus pre-compressed .gz/.br. Nginx serves the
#   collected files directly (fast path); WhiteNoise is the in-app fallback.
# Development: plain StaticFilesStorage so `collectstatic`/manifest is not
#   required locally and the whitenoise package need not be installed.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

# Media files (user uploads) - served by Nginx in production.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cache backend.
# Production: Redis via django-redis when DJANGO_REDIS_CACHE_URL is set
#   (e.g. redis://127.0.0.1:6379/1).
# Development: local-memory cache - no Redis server or extra package required.
_redis_cache_url = os.environ.get('DJANGO_REDIS_CACHE_URL', '').strip()
if _redis_cache_url:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': _redis_cache_url,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': 'hengjiams',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'hengjiams-dev',
        }
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
AUTH_USER_MODEL = 'accounts.User'  # Custom user model

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Two-Factor Authentication settings
OTP_TOTP_ISSUER = 'HengJi AMS'
OTP_LOGIN_URL = '/login/'

# Session settings
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Security settings for production
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Asset management specific settings
ASSET_PHOTO_UPLOAD_PATH = 'assets/photos/'
ASSET_BARCODE_UPLOAD_PATH = 'assets/barcodes/'
MAX_UPLOAD_SIZE = 5242880  # 5MB

# Email settings (for notifications)
EMAIL_BACKEND = 'accounts.email_backends.DatabaseSMTPEmailBackend'
DEFAULT_FROM_EMAIL = ''

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'hengjiams.log',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'assets': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
