# Generated by Django 5.2.3 on 2025-07-07 05:20

import assets.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Brand Name')),
                ('code', models.CharField(help_text='Short code for the brand (e.g., DELL, HP, APPLE)', max_length=50, unique=True, verbose_name='Brand Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='Support Email')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='Support Phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Asset Brand',
                'verbose_name_plural': 'Asset Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_number', models.CharField(help_text='Unique identifier for the asset', max_length=100, unique=True, verbose_name='Asset Number')),
                ('name', models.CharField(max_length=255, verbose_name='Asset Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('serial_number', models.CharField(blank=True, max_length=255, verbose_name='Serial Number')),
                ('barcode', models.CharField(blank=True, help_text='Barcode for scanning', max_length=255, unique=True, verbose_name='Barcode')),
                ('current_location', models.CharField(blank=True, help_text='Physical location of the asset', max_length=255, verbose_name='Current Location')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('repair', 'Under Repair'), ('retired', 'Retired'), ('disposed', 'Disposed'), ('lost', 'Lost'), ('stolen', 'Stolen')], default='available', max_length=20, verbose_name='Status')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=20, verbose_name='Condition')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchase Price')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Current Value')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date')),
                ('warranty_start_date', models.DateField(blank=True, null=True, verbose_name='Warranty Start Date')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Warranty End Date')),
                ('warranty_provider', models.CharField(blank=True, max_length=255, verbose_name='Warranty Provider')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=assets.models.asset_photo_upload_path, verbose_name='Photo')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_audit_date', models.DateTimeField(blank=True, null=True, verbose_name='Last Audit Date')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='companies.division', verbose_name='Division')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetbrand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Assigned Date')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='Expected Return Date')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='Returned Date')),
                ('assignment_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], max_length=20, verbose_name='Condition at Assignment')),
                ('return_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], max_length=20, verbose_name='Condition at Return')),
                ('assignment_notes', models.TextField(blank=True, verbose_name='Assignment Notes')),
                ('return_notes', models.TextField(blank=True, verbose_name='Return Notes')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset', verbose_name='Asset')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_processed', to=settings.AUTH_USER_MODEL, verbose_name='Returned By')),
            ],
            options={
                'verbose_name': 'Asset Assignment',
                'verbose_name_plural': 'Asset Assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('code', models.CharField(help_text='Unique code for the category (e.g., LAPTOP, PHONE)', max_length=50, unique=True, verbose_name='Category Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('requires_serial_number', models.BooleanField(default=True, help_text='Whether assets in this category must have a serial number', verbose_name='Requires Serial Number')),
                ('default_warranty_months', models.PositiveIntegerField(default=12, help_text='Default warranty period in months for this category', verbose_name='Default Warranty (Months)')),
                ('depreciation_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Annual depreciation rate as percentage', max_digits=5, verbose_name='Depreciation Rate (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='assets.assetcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Maintenance'), ('repair', 'Repair'), ('upgrade', 'Upgrade'), ('inspection', 'Inspection'), ('calibration', 'Calibration')], max_length=20, verbose_name='Maintenance Type')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('scheduled_date', models.DateTimeField(verbose_name='Scheduled Date')),
                ('started_date', models.DateTimeField(blank=True, null=True, verbose_name='Started Date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('vendor', models.CharField(blank=True, max_length=255, verbose_name='Vendor/Service Provider')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimated Cost')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Actual Cost')),
                ('work_performed', models.TextField(blank=True, verbose_name='Work Performed')),
                ('parts_replaced', models.TextField(blank=True, verbose_name='Parts Replaced')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Next Maintenance Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.asset', verbose_name='Asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Asset Maintenance',
                'verbose_name_plural': 'Asset Maintenance Records',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Model Name')),
                ('model_number', models.CharField(help_text='Official model number from manufacturer', max_length=100, verbose_name='Model Number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Technical specifications as JSON', verbose_name='Specifications')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='assets.assetbrand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Asset Model',
                'verbose_name_plural': 'Asset Models',
                'ordering': ['brand__name', 'name'],
                'unique_together': {('brand', 'model_number')},
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetmodel', verbose_name='Model'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_number'], name='assets_asse_asset_n_5a20c7_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='assets_asse_serial__401a52_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['barcode'], name='assets_asse_barcode_ea7ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_asse_status_347ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company'], name='assets_asse_company_492af9_idx'),
        ),
    ]
