# Generated by Django 5.2.3 on 2025-07-05 09:10

import assets.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the brand or manufacturer', max_length=100, unique=True, verbose_name='Brand Name')),
                ('code', models.CharField(help_text='Short code for the brand (e.g., DELL, HP, APPLE)', max_length=10, unique=True, verbose_name='Brand Code')),
                ('website', models.URLField(blank=True, help_text='Official website of the brand', verbose_name='Website')),
                ('support_email', models.EmailField(blank=True, help_text='Support email for warranty and technical issues', max_length=254, verbose_name='Support Email')),
                ('support_phone', models.CharField(blank=True, help_text='Support phone number', max_length=17, verbose_name='Support Phone')),
                ('logo', models.ImageField(blank=True, help_text='Brand logo image', null=True, upload_to='brands/logos/', verbose_name='Brand Logo')),
                ('default_warranty_years', models.PositiveIntegerField(default=1, help_text="Default warranty period for this brand's products", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Default Warranty Years')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this brand is active for new assets', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Asset Brand',
                'verbose_name_plural': 'Asset Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_number', models.CharField(help_text='Unique asset identifier (e.g., ACME-LAP-001)', max_length=50, unique=True, verbose_name='Asset Number')),
                ('serial_number', models.CharField(blank=True, help_text="Manufacturer's serial number", max_length=100, verbose_name='Serial Number')),
                ('barcode', models.CharField(blank=True, help_text='Barcode for mobile scanning', max_length=100, null=True, unique=True, verbose_name='Barcode')),
                ('name', models.CharField(help_text='Descriptive name of the asset', max_length=200, verbose_name='Asset Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the asset', verbose_name='Description')),
                ('model', models.CharField(help_text='Product model or part number', max_length=100, verbose_name='Model')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Original purchase price of the asset', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Purchase Price')),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current estimated value of the asset', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Current Value')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('warranty_start_date', models.DateField(blank=True, null=True, verbose_name='Warranty Start Date')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Warranty End Date')),
                ('warranty_provider', models.CharField(blank=True, help_text='Company or organization providing warranty', max_length=200, verbose_name='Warranty Provider')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('repair', 'Under Repair'), ('retired', 'Retired'), ('disposed', 'Disposed'), ('lost', 'Lost'), ('stolen', 'Stolen')], default='available', max_length=20, verbose_name='Status')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('broken', 'Broken')], default='good', max_length=20, verbose_name='Condition')),
                ('assigned_date', models.DateTimeField(blank=True, help_text='Date when asset was assigned to current user', null=True, verbose_name='Assigned Date')),
                ('primary_photo', models.ImageField(blank=True, help_text='Primary photo of the asset', null=True, upload_to=assets.models.asset_photo_upload_path, verbose_name='Primary Photo')),
                ('supplier', models.CharField(blank=True, help_text='Company or vendor that supplied this asset', max_length=200, verbose_name='Supplier')),
                ('purchase_order', models.CharField(blank=True, help_text='Purchase order number for this asset', max_length=100, verbose_name='Purchase Order')),
                ('depreciation_years', models.PositiveIntegerField(help_text='Number of years for depreciation calculation', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Depreciation Years')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this asset', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User currently assigned to this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='companies.division', verbose_name='Division')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='companies.location', verbose_name='Location')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetbrand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['asset_number'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Assigned Date')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='Returned Date')),
                ('assignment_notes', models.TextField(blank=True, help_text='Notes about the assignment', verbose_name='Assignment Notes')),
                ('return_notes', models.TextField(blank=True, help_text='Notes about the return', verbose_name='Return Notes')),
                ('condition_at_assignment', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('broken', 'Broken')], default='good', max_length=20, verbose_name='Condition at Assignment')),
                ('condition_at_return', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('broken', 'Broken')], max_length=20, verbose_name='Condition at Return')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='assets.asset', verbose_name='Asset')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_assignment_history', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_returns_processed', to=settings.AUTH_USER_MODEL, verbose_name='Returned By')),
            ],
            options={
                'verbose_name': 'Asset Assignment History',
                'verbose_name_plural': 'Asset Assignment Histories',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the asset category (e.g., Laptops, Servers, Furniture)', max_length=100, unique=True, verbose_name='Category Name')),
                ('code', models.CharField(help_text='Short code for the category (e.g., LAP, SRV, FUR)', max_length=10, unique=True, verbose_name='Category Code')),
                ('description', models.TextField(blank=True, help_text='Description of what assets belong to this category', verbose_name='Description')),
                ('default_depreciation_years', models.PositiveIntegerField(default=3, help_text='Default number of years for asset depreciation', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Default Depreciation Years')),
                ('icon', models.CharField(blank=True, help_text='CSS icon class for display (e.g., fas fa-laptop)', max_length=50, verbose_name='Icon Class')),
                ('color', models.CharField(default='#007bff', help_text='Hex color code for category display', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active for new assets', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='assets.assetcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('warranty', 'Warranty Document'), ('manual', 'User Manual'), ('receipt', 'Purchase Receipt'), ('invoice', 'Invoice'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=20, verbose_name='Document Type')),
                ('title', models.CharField(help_text='Descriptive title for the document', max_length=200, verbose_name='Title')),
                ('file', models.FileField(upload_to=assets.models.asset_document_upload_path, verbose_name='File')),
                ('description', models.TextField(blank=True, help_text='Description of the document contents', verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset', verbose_name='Asset')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Asset Document',
                'verbose_name_plural': 'Asset Documents',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=assets.models.asset_photo_upload_path, verbose_name='Photo')),
                ('caption', models.CharField(blank=True, help_text='Description of what this photo shows', max_length=200, verbose_name='Caption')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='assets.asset', verbose_name='Asset')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Asset Photo',
                'verbose_name_plural': 'Asset Photos',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_number'], name='assets_asse_asset_n_5a20c7_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='assets_asse_serial__401a52_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['barcode'], name='assets_asse_barcode_ea7ab8_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_asse_status_347ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['company'], name='assets_asse_company_492af9_idx'),
        ),
    ]
