# Generated by Django 5.2.3 on 2025-07-07 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('companies', '0003_companyuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetassignment',
            old_name='assignment_notes',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Physical location where the asset is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='companies.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='assignment_type',
            field=models.CharField(choices=[('user', 'User Assignment'), ('location', 'Location Assignment'), ('unassigned', 'Unassigned')], default='user', max_length=20, verbose_name='Assignment Type'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='companies.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User to whom this asset is assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_location',
            field=models.CharField(blank=True, help_text='Physical location of the asset - deprecated, use Location field', max_length=255, verbose_name='Current Location (Legacy)'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To User'),
        ),
        migrations.AlterField(
            model_name='assetassignment',
            name='assignment_condition',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], max_length=20, verbose_name='Condition at Assignment'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['asset', 'assigned_date'], name='assets_asse_asset_i_a867d8_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['assigned_to', 'returned_date'], name='assets_asse_assigne_70e7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassignment',
            index=models.Index(fields=['location', 'assigned_date'], name='assets_asse_locatio_dc616b_idx'),
        ),
    ]
