# Generated by Django 5.2 on 2025-08-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_assignment_notes_assetassignment_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(blank=True, help_text='Unique identifier for the asset (auto-generated if left blank)', max_length=100, unique=True, verbose_name='Asset Number'),
        ),
    ]
