# Generated by Django 5.2 on 2025-08-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_asset_name_alter_asset_asset_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(max_length=255, verbose_name='Serial Number'),
        ),
    ]
