# Generated by Django 5.2 on 2025-08-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_make_AssetSN_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='model_number',
            field=models.CharField(blank=True, help_text='Official model number from manufacturer', max_length=100, verbose_name='Model Number'),
        ),
    ]
