# Generated by Django 5.2.8 on 2026-04-15 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_assetmodel_model_number'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='source_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_assets', to='quotations.quotation', verbose_name='Source Quotation'),
        ),
    ]
