# Generated by Django 5.2.8 on 2026-04-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_source_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='unit',
            field=models.CharField(default='PCS', help_text='Default unit for this model (e.g., PCS, SET, KG)', max_length=50, verbose_name='Unit'),
        ),
    ]
