# Generated by Django 5.2.8 on 2026-04-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_assetmodel_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Serial Number'),
        ),
    ]
