# Generated by Django 5.2.8 on 2026-04-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_asset_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode for scanning', max_length=255, null=True, unique=True, verbose_name='Barcode'),
        ),
    ]
