# Generated by Django 5.2.8 on 2026-04-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_asset_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='model_number',
            field=models.CharField(blank=True, help_text='Official model number from manufacturer', max_length=100, null=True, verbose_name='Model Number'),
        ),
    ]
