# Generated by Django 5.2.8 on 2026-04-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_assetmodel_model_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location_rack',
            field=models.CharField(blank=True, help_text='Exact warehouse rack for this asset', max_length=50, null=True, verbose_name='Location Rack'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location_shelf',
            field=models.CharField(blank=True, help_text='Exact warehouse shelf for this asset', max_length=50, null=True, verbose_name='Location Shelf'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location_zone',
            field=models.CharField(blank=True, help_text='Exact warehouse zone for this asset', max_length=50, null=True, verbose_name='Location Zone'),
        ),
    ]
