# Generated by Django 5.2.8 on 2026-04-20 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_asset_location_rack_asset_location_shelf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Default category used for filtering in asset create forms', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_models', to='assets.assetcategory', verbose_name='Category'),
        ),
    ]
