# Generated by Django 5.2.8 on 2026-04-24 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_assetmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='default_asset_model',
            field=models.ForeignKey(blank=True, help_text='Used when RFQ requests only specify a generic device type for this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_categories', to='assets.assetmodel', verbose_name='Default Asset Model'),
        ),
    ]
