# Generated by Django 5.2.8 on 2026-04-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_assetcategory_default_asset_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='item_type',
            field=models.CharField(choices=[('hardware', 'Hardware'), ('service', 'Service')], default='hardware', help_text='Determines whether this category represents hardware or a service.', max_length=20, verbose_name='Item Type'),
        ),
    ]
