# Generated by Django 5.2.8 on 2026-09-21 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_assetcategory_item_type'),
        ('companies', '0014_company_default_quotation_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('assign', 'Assign Asset'), ('return', 'Return Asset'), ('export', 'Data Export'), ('import', 'Data Import')], max_length=20, verbose_name='Operation')),
                ('description', models.TextField(verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('asset', models.ForeignKey(blank=True, help_text='Null for bulk export/import events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='assets.asset', verbose_name='Asset')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_activity_logs', to='companies.company', verbose_name='Company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Asset Activity Log',
                'verbose_name_plural': 'Asset Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetFieldChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, verbose_name='New Value')),
                ('field_type', models.CharField(blank=True, max_length=50, verbose_name='Field Type')),
                ('activity_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_changes', to='assets.assetactivitylog', verbose_name='Activity Log')),
            ],
            options={
                'verbose_name': 'Asset Field Change',
                'verbose_name_plural': 'Asset Field Changes',
                'ordering': ['field_name'],
            },
        ),
        migrations.AddIndex(
            model_name='assetactivitylog',
            index=models.Index(fields=['asset', '-created_at'], name='assets_asse_asset_i_fe45af_idx'),
        ),
        migrations.AddIndex(
            model_name='assetactivitylog',
            index=models.Index(fields=['operation', '-created_at'], name='assets_asse_operati_c19c95_idx'),
        ),
        migrations.AddIndex(
            model_name='assetactivitylog',
            index=models.Index(fields=['company', '-created_at'], name='assets_asse_company_b87a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='assetactivitylog',
            index=models.Index(fields=['user', '-created_at'], name='assets_asse_user_id_28f583_idx'),
        ),
    ]
