# Generated by Django 5.2.8 on 2026-04-15 07:13

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Receipt Number')),
                ('receipt_date', models.DateField(default=datetime.date.today, verbose_name='Receipt Date')),
                ('received_by', models.CharField(max_length=200, verbose_name='Received By')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Received'), ('complete', 'Completely Received')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='quotations.quotation', verbose_name='Source Quotation')),
            ],
            options={
                'verbose_name': 'Purchase Receipt',
                'verbose_name_plural': 'Purchase Receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
