# Generated by Django 5.2.8 on 2026-04-16 03:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_source_quotation'),
        ('companies', '0006_make_division_code_optional'),
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='companies.location', verbose_name='Receipt Location'),
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='received_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Received Count'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='PO Number')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('receiving', 'Receiving'), ('complete', 'Complete')], default='ordered', max_length=20, verbose_name='Status')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Total Items')),
                ('total_received', models.PositiveIntegerField(default=0, verbose_name='Total Received')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order', to='quotations.quotation', verbose_name='Source Quotation')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchases.purchaseorder', verbose_name='Purchase Order'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField(blank=True, verbose_name='Product Description')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Unit')),
                ('quantity_ordered', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity Ordered')),
                ('quantity_received', models.PositiveIntegerField(default=0, verbose_name='Quantity Received')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Unit Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='assets.assetbrand', verbose_name='Brand')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='assets.assetmodel', verbose_name='Model')),
                ('product_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='products.productprice', verbose_name='Product Price')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder', verbose_name='Purchase Order')),
                ('quotation_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_item', to='quotations.quotationitem', verbose_name='Source Quotation Item')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'ordering': ['id'],
            },
        ),
    ]
