# Generated by Django 5.2.3 on 2025-07-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('companies', '0004_alter_division_manager_alter_location_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Superadmin'), ('manager', 'Manager'), ('it_specialist', 'IT Specialist'), ('viewer', 'Viewer')], help_text='Role for administrator access levels', max_length=20, null=True, verbose_name='Administrator Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_company',
            field=models.ForeignKey(blank=True, help_text='Company this manager has access to (for Manager role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='companies.company', verbose_name='Managed Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_divisions',
            field=models.ManyToManyField(blank=True, help_text='Divisions this IT specialist has access to', related_name='it_specialists', to='companies.division', verbose_name='Managed Divisions'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_locations',
            field=models.ManyToManyField(blank=True, help_text='Locations this viewer has read-only access to', related_name='viewers', to='companies.location', verbose_name='Managed Locations'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer')], default='staff', max_length=20, verbose_name='Legacy Role'),
        ),
    ]
