# Generated by Django 5.2 on 2025-07-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_admin_role_user_managed_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='User must change password on next login', verbose_name='Must Change Password'),
        ),
    ]
