# Generated by Django 5.2 on 2025-08-13 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_legacy_role'),
        ('companies', '0004_alter_division_manager_alter_location_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Superadmin'), ('it_administrator', 'IT Administrator'), ('viewer', 'Viewer')], help_text='Role for administrator access levels', max_length=20, null=True, verbose_name='Administrator Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='managed_company',
            field=models.ForeignKey(blank=True, help_text='Company this IT administrator has access to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_administrators', to='companies.company', verbose_name='Managed Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='managed_divisions',
            field=models.ManyToManyField(blank=True, help_text='Divisions this IT administrator has access to', related_name='it_administrators', to='companies.division', verbose_name='Managed Divisions'),
        ),
    ]
