# Generated by Django 5.2 on 2025-08-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_admin_role_alter_user_managed_company_and_more'),
    ]

    operations = [
    ]
