# Generated by Django 5.2 on 2025-08-13 09:07

from django.db import migrations


def update_user_roles(apps, schema_editor):
    """
    Update existing users with old role names to new role names:
    - 'manager' -> remove (delete users with this role or convert to it_administrator)  
    - 'it_specialist' -> 'it_administrator'
    """
    User = apps.get_model('accounts', 'User')
    
    # Update IT Specialist to IT Administrator
    User.objects.filter(admin_role='it_specialist').update(admin_role='it_administrator')
    
    # Remove Manager role users (or convert them to IT Administrator)
    # Option 1: Convert managers to IT Administrator
    User.objects.filter(admin_role='manager').update(admin_role='it_administrator')
    
    # Option 2: Delete manager users (uncomment if preferred)
    # User.objects.filter(admin_role='manager').delete()


def reverse_user_roles(apps, schema_editor):
    """
    Reverse the role changes for rollback
    """
    User = apps.get_model('accounts', 'User')
    
    # Reverse IT Administrator to IT Specialist
    User.objects.filter(admin_role='it_administrator').update(admin_role='it_specialist')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_update_roles_to_it_administrator'),
    ]

    operations = [
        migrations.RunPython(update_user_roles, reverse_user_roles),
    ]
