# Generated by Django 5.2.8 on 2026-04-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_migrate_roles_to_it_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_2fa_setup',
            field=models.BooleanField(default=False, help_text='User must set up 2FA on next login', verbose_name='Force 2FA Setup'),
        ),
    ]
