# Generated by Django 5.2.8 on 2026-04-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_mailbox_sync_window_and_outbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedemailmessage',
            name='rfq_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='RFQ Confidence'),
        ),
        migrations.AddField(
            model_name='receivedemailmessage',
            name='rfq_error',
            field=models.TextField(blank=True, verbose_name='RFQ Error'),
        ),
        migrations.AddField(
            model_name='receivedemailmessage',
            name='rfq_extracted_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='RFQ Extracted Data'),
        ),
        migrations.AddField(
            model_name='receivedemailmessage',
            name='rfq_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='RFQ Processed At'),
        ),
        migrations.AddField(
            model_name='receivedemailmessage',
            name='rfq_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('classified_rfq', 'Classified RFQ'), ('classified_non_rfq', 'Classified Non-RFQ'), ('quotation_drafted', 'Quotation Drafted'), ('quotation_confirmed', 'Quotation Confirmed'), ('classification_failed', 'Classification Failed')], default='unreviewed', max_length=40, verbose_name='RFQ Status'),
        ),
        migrations.AddField(
            model_name='receivedemailmessage',
            name='rfq_summary',
            field=models.TextField(blank=True, verbose_name='RFQ Summary'),
        ),
        migrations.AddIndex(
            model_name='receivedemailmessage',
            index=models.Index(fields=['rfq_status', '-rfq_processed_at'], name='accounts_re_rfq_sta_12aa42_idx'),
        ),
        migrations.AddIndex(
            model_name='receivedemailmessage',
            index=models.Index(fields=['direction', 'rfq_status'], name='accounts_re_directi_c147e4_idx'),
        ),
    ]
