# Generated by Django 5.2.8 on 2026-09-07 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_encrypt_mailbox_passwords_with_fernet'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appid', models.CharField(help_text='Mini-program AppID this openid belongs to.', max_length=64, verbose_name='WeChat AppID')),
                ('openid', models.CharField(max_length=128, verbose_name='OpenID')),
                ('unionid', models.CharField(blank=True, max_length=128, verbose_name='UnionID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_identities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'WeChat Identity',
                'verbose_name_plural': 'WeChat Identities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'appid'], name='accounts_we_user_id_ca7436_idx')],
                'constraints': [models.UniqueConstraint(fields=('appid', 'openid'), name='uniq_wechat_appid_openid')],
            },
        ),
    ]
