# Generated by Django 5.2.8 on 2026-09-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_wechatidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=80, unique=True, verbose_name='City (English)')),
                ('name_zh', models.CharField(blank=True, max_length=80, verbose_name='City (Chinese)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Service City',
                'verbose_name_plural': 'Service Cities',
                'ordering': ['name_en'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='chinese_name',
            field=models.CharField(blank=True, db_index=True, help_text='Simplified-Chinese name; the mini program login looks engineers up by this.', max_length=100, verbose_name='Chinese Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='service_cities',
            field=models.ManyToManyField(blank=True, help_text='Cities/regions this field engineer covers (select multiple).', related_name='engineers', to='accounts.servicecity', verbose_name='Service Cities'),
        ),
    ]
