# Generated by Django 5.2.8 on 2026-09-23 05:24

from django.db import migrations, models


def rename_inspection_engineer_role(apps, schema_editor):
    """Relabel the existing inspection_engineer role as 'Field Engineer'.

    The role code is unchanged (no user-role reassignment needed); only the
    human-readable name shown in role pickers is updated.
    """
    AdminRole = apps.get_model('accounts', 'AdminRole')
    AdminRole.objects.filter(code='inspection_engineer').update(name='Field Engineer')


def reverse_rename_role(apps, schema_editor):
    AdminRole = apps.get_model('accounts', 'AdminRole')
    AdminRole.objects.filter(code='inspection_engineer').update(name='Inspection Engineer')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_servicecity_user_chinese_name_user_service_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fe_notes',
            field=models.TextField(blank=True, help_text='Free-form notes tracking field-engineer quality.', verbose_name='Field Engineer Notes'),
        ),
        migrations.AddField(
            model_name='user',
            name='fe_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-5 quality rating tracked for field engineers.', null=True, verbose_name='Field Engineer Rating'),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, help_text='One-time invite id offered to a field engineer on first mini-program use.', max_length=16, null=True, unique=True, verbose_name='Invite Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_id',
            field=models.CharField(blank=True, db_index=True, help_text='WeChat account id used to look up field engineers.', max_length=64, verbose_name='WeChat ID'),
        ),
        migrations.RunPython(rename_inspection_engineer_role, reverse_rename_role),
    ]
