"""
Tests for the Kering store-inspection domain: models, report transforms, and the
report/photo generation service.
"""
import io
import os
import tempfile
from datetime import date
from unittest import mock

import pandas as pd
from django.contrib.auth import get_user_model
from django.core.files.base import ContentFile
from django.core.management import call_command
from django.test import TestCase, override_settings
from openpyxl import load_workbook
from PIL import Image

from assets.models import Asset
from companies.models import Company, Division, Location
from inspections.constants import COVER_PAGE_DEVICE_LABELS, STATUS_IN_STORE, STATUS_NOT_IN_STORE
from inspections.models import InspectionDevice, InspectionPhoto, StoreInspection
from inspections.services import transforms
from inspections.services.photo_naming import assign_photo_display_names
from inspections.services.report_generator import generate_inspection_report

User = get_user_model()

TEMP_MEDIA = tempfile.mkdtemp(prefix='inspections-test-media-')


def _png_bytes(color='red'):
    buffer = io.BytesIO()
    Image.new('RGB', (8, 8), color).save(buffer, format='PNG')
    return buffer.getvalue()


class InspectionFixtureMixin:
    def make_inspection(self):
        company = Company.objects.create(name='Kering', code='KER')
        division = Division.objects.create(company=company, name='Gucci', code='GUCCI')
        location = Location.objects.create(
            company=company, division=division, name='SZOL', code='22149',
            location_type=Location.LocationType.STORE,
        )
        engineer = User.objects.create_user(username='sean', password='pw')
        inspection = StoreInspection.objects.create(
            company=company, division=division, location=location, jda_code='22149',
            brand_name='Gucci', store_name='SZOL', inspection_date=date(2026, 9, 2),
            engineer=engineer,
        )
        return inspection

    def make_device(self, inspection, **kwargs):
        defaults = {
            'client_device_uid': kwargs.pop('uid', None) or f'uid-{InspectionDevice.objects.count()}',
            'category': 'Desktop', 'brand_model': 'Lenovo-M70Q', 'sn': 'PC1',
            'asset_id_text': 'CGDR-1', 'usage': 'xstore',
        }
        defaults.update(kwargs)
        return InspectionDevice.objects.create(store_inspection=inspection, **defaults)


@override_settings(MEDIA_ROOT=TEMP_MEDIA)
class ModelTests(InspectionFixtureMixin, TestCase):
    def test_store_label_autogenerated(self):
        inspection = self.make_inspection()
        self.assertEqual(inspection.store_label, '22149 Gucci SZOL')

    def test_completion_percentage(self):
        from django.utils import timezone
        inspection = self.make_inspection()
        self.make_device(inspection, uid='a')
        self.make_device(inspection, uid='b')
        self.assertEqual(inspection.get_completion_percentage(), 0)
        device = inspection.devices.get(client_device_uid='a')
        device.collected_at = timezone.now()
        device.save()
        self.assertEqual(inspection.get_completion_percentage(), 50.0)

    def test_device_uid_autofill_and_unique(self):
        inspection = self.make_inspection()
        device = InspectionDevice.objects.create(store_inspection=inspection, category='Monitor', sn='M1')
        self.assertTrue(device.client_device_uid)
        # A second device gets a different auto uid (unique constraint holds).
        other = InspectionDevice.objects.create(store_inspection=inspection, category='Monitor', sn='M2')
        self.assertNotEqual(device.client_device_uid, other.client_device_uid)

    def test_category_normalized_on_save(self):
        inspection = self.make_inspection()
        device = self.make_device(inspection, category='iPhone', brand_model='iPhone SE', sn='IP1')
        self.assertEqual(device.category, 'IOS_Device')


class TransformTests(InspectionFixtureMixin, TestCase):
    def test_effective_status_uncollected_expected_is_not_in_store(self):
        inspection = self.make_inspection()
        device = self.make_device(inspection)
        self.assertEqual(transforms.effective_status(device), STATUS_NOT_IN_STORE)

    def test_effective_status_collected_is_in_store(self):
        from django.utils import timezone
        inspection = self.make_inspection()
        device = self.make_device(inspection)
        device.collected_at = timezone.now()
        self.assertEqual(transforms.effective_status(device), STATUS_IN_STORE)

    def test_effective_status_explicit_not_in_store(self):
        inspection = self.make_inspection()
        device = self.make_device(inspection, status='not_in_store')
        device.collected_at = None
        self.assertEqual(transforms.effective_status(device), STATUS_NOT_IN_STORE)

    def test_intact_tag_autofill(self):
        inspection = self.make_inspection()
        device = self.make_device(inspection, intact_asset_tag='', asset_id_text='')
        self.assertEqual(transforms.autofill_intact_tag(device), 'N')
        device.intact_asset_tag = 'Y'
        self.assertEqual(transforms.autofill_intact_tag(device), 'Y')

    def test_merged_version(self):
        inspection = self.make_inspection()
        device = self.make_device(inspection, windows_version='Win11', ios_version='')
        self.assertEqual(transforms.merged_version(device), 'Win11')

    def test_cover_page_counts(self):
        from django.utils import timezone
        inspection = self.make_inspection()
        now = timezone.now()
        d1 = self.make_device(inspection, uid='d1', category='Desktop', usage='xstore')
        d2 = self.make_device(inspection, uid='d2', category='Monitor', usage='xstore', sn='M1')
        d1.collected_at = now
        d2.collected_at = now
        counts = transforms.build_cover_page_summary_counts([d1, d2])
        self.assertEqual(counts['Xstore PC'], 1)
        self.assertEqual(counts['Monitor'], 1)
        self.assertEqual(sum(counts.values()), 2)
        self.assertIn('Monitor', COVER_PAGE_DEVICE_LABELS)

    def test_xstore_peripheral_linking(self):
        inspection = self.make_inspection()
        host = self.make_device(inspection, uid='host', category='Desktop', usage='xstore', asset_id_text='CGDR-HOST')
        peripheral = self.make_device(inspection, uid='per', category='Scanner', usage='xstore-1', sn='SC1')
        transforms.link_xstore_peripherals([host, peripheral])
        self.assertIn('PC: CGDR-HOST', peripheral.comment)

    def test_monitor_size_comment_markers(self):
        inspection = self.make_inspection()
        d1 = self.make_device(inspection, uid='m1', category='Monitor', brand_model='Lenovo-L1710', sn='MON1')
        self.assertEqual(transforms.apply_monitor_size_comment(d1), '17-in')
        d2 = self.make_device(inspection, uid='m2', category='Monitor', brand_model='Lenovo TE20-10', sn='MON2')
        self.assertEqual(transforms.apply_monitor_size_comment(d2), '19.5-in')
        # Existing comment is preserved and the marker appended; unknown models untouched.
        d3 = self.make_device(inspection, uid='m3', category='Monitor', brand_model='Lenovo-L1710', sn='MON3', comment='设备老旧')
        self.assertEqual(transforms.apply_monitor_size_comment(d3), '设备老旧; 17-in')
        d4 = self.make_device(inspection, uid='m4', category='Monitor', brand_model='Unknown-X', sn='MON4', comment='keep')
        self.assertEqual(transforms.apply_monitor_size_comment(d4), 'keep')

    def test_new_device_marker(self):
        inspection = self.make_inspection()
        device = self.make_device(inspection, uid='nd1', category='Monitor', sn='NEW1')
        device.is_new_device = True
        self.assertEqual(transforms.apply_new_device_marker(device, ''), 'NEW')
        self.assertEqual(transforms.apply_new_device_marker(device, 'broken'), 'broken; NEW')
        # Idempotent: an existing NEW token is not duplicated.
        self.assertEqual(transforms.apply_new_device_marker(device, 'NEW'), 'NEW')
        device.is_new_device = False
        self.assertEqual(transforms.apply_new_device_marker(device, 'ok'), 'ok')


@override_settings(MEDIA_ROOT=TEMP_MEDIA)
class ReportGeneratorTests(InspectionFixtureMixin, TestCase):
    def test_generate_report_creates_four_sheets_and_rows(self):
        from django.utils import timezone
        inspection = self.make_inspection()
        device = self.make_device(inspection, uid='r1', category='Desktop', brand_model='Lenovo-M70Q',
                                   sn='PC1', asset_id_text='CGDR-1', usage='xstore',
                                   ip_address='10.0.0.5', cpu='i5', memory='16G', hdd='512G')
        device.collected_at = timezone.now()
        device.save()

        generate_inspection_report(inspection)
        inspection.refresh_from_db()
        self.assertTrue(inspection.report_file)
        self.assertIsNotNone(inspection.report_generated_at)

        workbook = load_workbook(inspection.report_file.path)
        for sheet in ('inspection_items', 'confirmation_page', 'cover_page', 'asset_list'):
            self.assertIn(sheet, workbook.sheetnames)
        asset_sheet = workbook['asset_list']
        header = [cell.value for cell in asset_sheet[1]]
        self.assertIn('SN', header)
        self.assertIn('Intact Asset Tag', header)
        # The collected device appears as an In Store row with its SN.
        body = '\n'.join(str(cell.value) for row in asset_sheet.iter_rows(min_row=2) for cell in row)
        self.assertIn('PC1', body)
        self.assertIn('In Store', body)

    def test_photo_display_names(self):
        inspection = self.make_inspection()
        device = self.make_device(inspection, uid='p1', category='Desktop', sn='PC9')
        overall = InspectionPhoto(store_inspection=inspection, device=device, kind='overall', sort_index=1)
        overall.image.save('overall.png', ContentFile(_png_bytes()), save=False)
        overall.save()
        serial = InspectionPhoto(store_inspection=inspection, device=device, kind='serial', sort_index=2)
        serial.image.save('serial.png', ContentFile(_png_bytes('blue')), save=False)
        serial.save()
        rack = InspectionPhoto(store_inspection=inspection, kind='rack1', sort_index=1)
        rack.image.save('rack.png', ContentFile(_png_bytes('green')), save=False)
        rack.save()

        photos = assign_photo_display_names(inspection)
        names = {p.kind: p.display_name for p in photos}
        self.assertEqual(names['overall'], 'DesktopPC9-1.png')
        self.assertEqual(names['serial'], 'DesktopPC9-2.png')
        self.assertEqual(names['rack1'], 'Rack1-1.png')

    def test_generate_report_packages_photo_zip(self):
        inspection = self.make_inspection()
        device = self.make_device(inspection, uid='z1', category='Monitor', sn='M9')
        photo = InspectionPhoto(store_inspection=inspection, device=device, kind='overall', sort_index=1)
        photo.image.save('m.png', ContentFile(_png_bytes()), save=False)
        photo.save()

        generate_inspection_report(inspection)
        inspection.refresh_from_db()
        self.assertTrue(inspection.photo_zip)
        import zipfile
        with zipfile.ZipFile(inspection.photo_zip.path) as zf:
            self.assertIn('Photo/MonitorM9-1.png', zf.namelist())

    def test_template_population_by_label(self):
        """Values land in the exact template cells (cover D-column, confirmation C-column)."""
        from django.utils import timezone
        from inspections.services.report_generator import TEMPLATE_PATH
        if not os.path.exists(TEMPLATE_PATH):
            self.skipTest('report_template.xlsx not bundled')

        inspection = self.make_inspection()
        inspection.brand_name = 'Gucci'
        inspection.error_setting_fixed_count = 3
        inspection.device_counts = {'显示器数量': 6}
        inspection.save()
        device = self.make_device(inspection, uid='t1', category='Monitor', sn='M1')
        device.collected_at = timezone.now()
        device.save()

        generate_inspection_report(inspection)
        inspection.refresh_from_db()
        workbook = load_workbook(inspection.report_file.path)

        cover = workbook['cover_page']
        self.assertEqual(cover['D5'].value, 'Gucci')       # Brand
        self.assertEqual(cover['D15'].value, 3)            # Error Setting Fixed
        self.assertEqual(cover['D44'].value, 1)            # Monitor count (1 collected monitor)

        confirmation = workbook['confirmation_page']
        monitor_count = None
        for row in range(1, confirmation.max_row + 1):
            label = str(confirmation.cell(row=row, column=1).value or '').strip()
            if label.startswith('显示器数量'):
                monitor_count = confirmation.cell(row=row, column=3).value
        self.assertEqual(monitor_count, 6)


@override_settings(MEDIA_ROOT=TEMP_MEDIA)
class ImportCommandTests(TestCase):
    """Phase 0: import the Kering schedule + master asset list."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix='kering-import-')
        self.schedule = os.path.join(self.tmp, 'schedule.xlsx')
        self.assets = os.path.join(self.tmp, 'assets.xlsx')
        pd.DataFrame([{
            'JDA code': '22149', 'Brand': 'Gucci', 'Store Name': 'SZOL', 'inspection_date': '2026-09-02',
        }]).to_excel(self.schedule, index=False)
        pd.DataFrame([
            {'STORE': 'SZOL', 'JDA': '22149', 'Asset ID': 'CGDR-1', 'Category': 'Desktop',
             'Brand-Model': 'Lenovo-M70Q', 'SN': 'PC1', 'Warranty-start': '2022-07-10',
             'Usage': 'xstore', 'Status': 'In Store', '照片需求': '需要拍照', '大纲': '电脑', '注释': ''},
            {'STORE': 'SZOL', 'JDA': '22149', 'Asset ID': '', 'Category': 'iPhone',
             'Brand-Model': 'iPhone SE', 'SN': 'IP1', 'Warranty-start': '',
             'Usage': 'AR/S2S/PI', 'Status': 'In Store', '照片需求': '无需拍照', '大纲': '苹果设备', '注释': ''},
        ]).to_excel(self.assets, index=False)

    def test_import_creates_inspection_devices_and_assets(self):
        call_command('import_kering_master', schedule=self.schedule, assets=self.assets)
        self.assertEqual(StoreInspection.objects.count(), 1)
        inspection = StoreInspection.objects.first()
        self.assertEqual(inspection.jda_code, '22149')
        self.assertEqual(inspection.store_label, '22149 Gucci SZOL')
        self.assertEqual(inspection.devices.count(), 2)
        # Device-category normalization: iPhone -> IOS_Device.
        self.assertTrue(inspection.devices.filter(category='IOS_Device').exists())
        # Photo-requirement mapping (需要拍照 -> True, 无需拍照 -> False).
        self.assertTrue(inspection.devices.get(sn='PC1').photo_required)
        self.assertFalse(inspection.devices.get(sn='IP1').photo_required)
        # Org structure + assets created.
        self.assertTrue(Company.objects.filter(name='Kering').exists())
        self.assertTrue(Location.objects.filter(code='22149').exists())
        self.assertTrue(Asset.objects.filter(serial_number='PC1').exists())

    def test_import_is_idempotent(self):
        call_command('import_kering_master', schedule=self.schedule, assets=self.assets)
        call_command('import_kering_master', schedule=self.schedule, assets=self.assets)
        self.assertEqual(StoreInspection.objects.count(), 1)
        self.assertEqual(InspectionDevice.objects.count(), 2)

    def test_dry_run_persists_nothing(self):
        call_command('import_kering_master', schedule=self.schedule, assets=self.assets, dry_run=True)
        self.assertEqual(StoreInspection.objects.count(), 0)
        self.assertEqual(InspectionDevice.objects.count(), 0)
        self.assertEqual(Asset.objects.count(), 0)

    def test_import_is_rollbackable(self):
        from companies.models import ImportRun
        from utils.import_rollback import rollback_run

        call_command('import_kering_master', schedule=self.schedule, assets=self.assets)
        run = ImportRun.objects.filter(module='inspections', import_type='kering_master').first()
        self.assertIsNotNone(run)
        self.assertTrue(run.can_rollback)

        rollback_run(run)
        self.assertEqual(StoreInspection.objects.count(), 0)
        self.assertEqual(InspectionDevice.objects.count(), 0)
        self.assertEqual(Asset.objects.count(), 0)
        self.assertEqual(Company.objects.filter(name='Kering').count(), 0)

    def test_no_track_rollback_skips_import_run(self):
        from companies.models import ImportRun

        call_command('import_kering_master', schedule=self.schedule, assets=self.assets, no_track_rollback=True)
        self.assertEqual(StoreInspection.objects.count(), 1)
        self.assertEqual(ImportRun.objects.filter(module='inspections', import_type='kering_master').count(), 0)

    def test_placeholder_sn_assigned_when_id_and_sn_blank(self):
        assets2 = os.path.join(self.tmp, 'assets2.xlsx')
        pd.DataFrame([
            {'STORE': 'SZOL', 'JDA': '22149', 'Asset ID': '', 'Category': 'Other',
             'Brand-Model': 'UPS SMC1000I-CH', 'SN': '', 'Warranty-start': '', 'Usage': 'Xstore',
             'Status': 'In Store', '照片需求': '需要拍照', '大纲': '其他', '注释': ''},
            {'STORE': 'SZOL', 'JDA': '22149', 'Asset ID': '', 'Category': 'Other',
             'Brand-Model': 'RFID Charger', 'SN': '', 'Warranty-start': '', 'Usage': 'AR/S2S/PI',
             'Status': 'In Store', '照片需求': '需要拍照', '大纲': '其他', '注释': ''},
        ]).to_excel(assets2, index=False)
        call_command('import_kering_master', schedule=self.schedule, assets=assets2)
        inspection = StoreInspection.objects.first()
        sns = sorted(inspection.devices.values_list('sn', flat=True))
        self.assertEqual(sns, ['placeholder-000001', 'placeholder-000002'])

    def test_brand_case_variants_share_one_brand(self):
        """Real data has case/whitespace brand variants that collide on UNIQUE code."""
        from assets.models import AssetBrand

        assets2 = os.path.join(self.tmp, 'assets_brand.xlsx')
        pd.DataFrame([
            {'STORE': 'SZOL', 'JDA': '22149', 'Asset ID': 'A1', 'Category': 'Printer',
             'Brand-Model': 'HP-P1108', 'SN': 'P1', 'Warranty-start': '', 'Usage': 'a4',
             'Status': 'In Store', '照片需求': '需要拍照', '大纲': '', '注释': ''},
            {'STORE': 'SZOL', 'JDA': '22149', 'Asset ID': 'A2', 'Category': 'Printer',
             'Brand-Model': 'hp-M479', 'SN': 'P2', 'Warranty-start': '', 'Usage': 'aio',
             'Status': 'In Store', '照片需求': '需要拍照', '大纲': '', '注释': ''},
        ]).to_excel(assets2, index=False)
        call_command('import_kering_master', schedule=self.schedule, assets=assets2)
        self.assertEqual(AssetBrand.objects.filter(code='HP').count(), 1)
        self.assertEqual(InspectionDevice.objects.count(), 2)

    def test_blank_warranty_nat_imports_as_null(self):
        """Blank dates come back from pandas as NaT and must import as NULL."""
        assets3 = os.path.join(self.tmp, 'assets_nat.xlsx')
        pd.DataFrame([
            {'STORE': 'SZOL', 'JDA': '22149', 'Asset ID': 'A3', 'Category': 'Desktop',
             'Brand-Model': 'Lenovo-M70Q', 'SN': 'D1', 'Warranty-start': date(2022, 7, 10),
             'Usage': 'xstore', 'Status': 'In Store', '照片需求': '需要拍照', '大纲': '', '注释': ''},
            {'STORE': 'SZOL', 'JDA': '22149', 'Asset ID': 'A4', 'Category': 'Desktop',
             'Brand-Model': 'Lenovo-M70Q', 'SN': 'D2', 'Warranty-start': None,
             'Usage': 'xstore', 'Status': 'In Store', '照片需求': '需要拍照', '大纲': '', '注释': ''},
        ]).to_excel(assets3, index=False)
        call_command('import_kering_master', schedule=self.schedule, assets=assets3)
        self.assertEqual(InspectionDevice.objects.get(sn='D1').warranty_start, date(2022, 7, 10))
        self.assertIsNone(InspectionDevice.objects.get(sn='D2').warranty_start)


@override_settings(MEDIA_ROOT=TEMP_MEDIA)
class ReportParityTests(InspectionFixtureMixin, TestCase):
    """Content parity against real rows from the golden `22149 Gucci SZOL` asset list.

    Validates that the ported transforms reproduce the expected normalized
    categories, In Store status, and cover-page counts for real Kering devices.
    """

    # (category, brand_model, sn, asset_id, usage) sampled from the golden file.
    GOLDEN_ROWS = [
        ('Monitor', 'Lenovo-L1710', '1S60FDHCR1CXU433P8KV', 'GCNLCD0233', 'Xstore'),
        ('Desktop', 'Lenovo-M720Q', 'PC225BDW', 'CGDR-PC225BDW', 'Xstore'),
        ('Scanner', 'Zebra DS2208', '23262010556981', 'CKSO-23262010556981', 'Xstore'),
        ('RFID', 'RFID 8500', '18265523022052', 'GCNRFS0196', 'AR/S2S/PI'),
        ('Printer', 'Epson TM-T88VI', 'X6XX019867', 'CGPR-X6XX019867', 'Xstore'),
        ('iPhone', 'iPhone SE', 'CQ41WPH23K', 'GGCNPH0229', 'AR/S2S/PI'),
    ]

    def _build(self):
        from django.utils import timezone
        inspection = self.make_inspection()
        for index, (category, brand_model, sn, asset_id, usage) in enumerate(self.GOLDEN_ROWS):
            InspectionDevice.objects.create(
                store_inspection=inspection, client_device_uid=f'g-{index}',
                category=category, brand_model=brand_model, sn=sn,
                asset_id_text=asset_id, usage=usage, collected_at=timezone.now(),
            )
        return inspection

    def test_asset_list_rows_and_normalized_categories(self):
        inspection = self._build()
        generate_inspection_report(inspection)
        inspection.refresh_from_db()
        sheet = load_workbook(inspection.report_file.path)['asset_list']
        body = [[cell.value for cell in row] for row in sheet.iter_rows(min_row=2)]
        by_sn = {row[5]: row for row in body if row[5]}
        # Every golden SN is present and reported In Store.
        for _cat, _bm, sn, _aid, _usage in self.GOLDEN_ROWS:
            self.assertIn(sn, by_sn)
            self.assertEqual(by_sn[sn][8], STATUS_IN_STORE)
        # Category normalization: RFID -> AR_Device, iPhone -> IOS_Device.
        self.assertEqual(by_sn['18265523022052'][3], 'AR_Device')
        self.assertEqual(by_sn['CQ41WPH23K'][3], 'IOS_Device')
        self.assertEqual(by_sn['1S60FDHCR1CXU433P8KV'][3], 'Monitor')

    def test_cover_page_counts_match_expected(self):
        inspection = self._build()
        counts = transforms.build_cover_page_summary_counts(list(inspection.devices.all()))
        self.assertEqual(counts['Monitor'], 1)
        self.assertEqual(counts['Xstore PC'], 1)
        self.assertEqual(counts['Xstore Scanner'], 1)
        self.assertEqual(counts['RFID'], 1)
        self.assertEqual(counts['Reception Printer'], 1)
        self.assertEqual(counts['iPhone se（total）'], 1)


@override_settings(MEDIA_ROOT=TEMP_MEDIA)
class HistoricalPhotoReuseTests(TestCase):
    def _make_store(self):
        company = Company.objects.create(name='Kering', code='KER')
        location = Location.objects.create(
            company=company, name='SZOL', code='22149', location_type=Location.LocationType.STORE,
        )
        prior = StoreInspection.objects.create(
            company=company, location=location, jda_code='22149', inspection_date=date(2025, 9, 1),
        )
        current = StoreInspection.objects.create(
            company=company, location=location, jda_code='22149', inspection_date=date(2026, 9, 1),
        )
        return prior, current

    def test_reuse_copies_by_sn_and_clears_photo_required(self):
        from inspections.services.historical_photos import reuse_historical_photos

        prior, current = self._make_store()
        prior_device = InspectionDevice.objects.create(
            store_inspection=prior, client_device_uid='p1', category='Monitor', sn='MON1', photo_required=True,
        )
        photo = InspectionPhoto(store_inspection=prior, device=prior_device, kind='overall', sort_index=1)
        photo.image.save('m.png', ContentFile(_png_bytes()), save=False)
        photo.save()

        current_device = InspectionDevice.objects.create(
            store_inspection=current, client_device_uid='c1', category='Monitor', sn='MON1', photo_required=True,
        )

        result = reuse_historical_photos(current)
        self.assertEqual(result['photos_copied'], 1)
        self.assertEqual(result['devices_matched'], 1)
        current_device.refresh_from_db()
        self.assertFalse(current_device.photo_required)
        self.assertEqual(current_device.photos.filter(kind='overall').count(), 1)

    def test_reuse_is_idempotent(self):
        from inspections.services.historical_photos import reuse_historical_photos

        prior, current = self._make_store()
        prior_device = InspectionDevice.objects.create(
            store_inspection=prior, client_device_uid='p1', category='Monitor', sn='MON2', photo_required=True,
        )
        photo = InspectionPhoto(store_inspection=prior, device=prior_device, kind='overall', sort_index=1)
        photo.image.save('m.png', ContentFile(_png_bytes()), save=False)
        photo.save()
        InspectionDevice.objects.create(
            store_inspection=current, client_device_uid='c1', category='Monitor', sn='MON2', photo_required=True,
        )

        reuse_historical_photos(current)
        reuse_historical_photos(current)
        self.assertEqual(InspectionPhoto.objects.filter(store_inspection=current).count(), 1)

    def test_no_prior_inspection_is_safe(self):
        from inspections.services.historical_photos import reuse_historical_photos

        company = Company.objects.create(name='Kering2', code='KER2')
        location = Location.objects.create(company=company, name='X', code='99999')
        lone = StoreInspection.objects.create(
            company=company, location=location, jda_code='99999', inspection_date=date(2026, 9, 1),
        )
        result = reuse_historical_photos(lone)
        self.assertIsNone(result['source_inspection'])
        self.assertEqual(result['photos_copied'], 0)


@override_settings(MEDIA_ROOT=TEMP_MEDIA)
class RealDataIntegrationTests(TestCase):
    """End-to-end on the REAL Kering master dataset (import -> report).

    Gated behind INSPECTION_REAL_DATA_TEST=1 so the default suite stays fast and
    CI (without the dataset) skips it. Runs inside a rolled-back transaction, so it
    never mutates the dev database.
    """

    SCHEDULE = (r'c:\Users\sean_\Documents\EUS_Device_Inspec\DeviceInspecProjectInitialization'
                r'\schedule.xlsx')
    ASSETS = (r'c:\Users\sean_\Documents\EUS_Device_Inspec\DeviceInspecProjectInitialization'
              r'\asset_list_CN_2026.xlsx')

    def setUp(self):
        if os.environ.get('INSPECTION_REAL_DATA_TEST') != '1':
            self.skipTest('set INSPECTION_REAL_DATA_TEST=1 to run the real-data integration test')
        if not (os.path.exists(self.SCHEDULE) and os.path.exists(self.ASSETS)):
            self.skipTest('real Kering dataset not available')

    def test_import_then_generate_report(self):
        from django.db.models import Count

        call_command('import_kering_master', schedule=self.SCHEDULE, assets=self.ASSETS,
                     no_track_rollback=True)
        self.assertGreater(StoreInspection.objects.count(), 50)
        self.assertGreater(InspectionDevice.objects.count(), 500)

        inspection = (
            StoreInspection.objects.annotate(n=Count('devices'))
            .filter(n__gt=5).order_by('-n').first()
        )
        self.assertIsNotNone(inspection)

        generate_inspection_report(inspection)
        inspection.refresh_from_db()
        self.assertTrue(inspection.report_file)

        workbook = load_workbook(inspection.report_file.path)
        for sheet in ('inspection_items', 'confirmation_page', 'cover_page', 'asset_list'):
            self.assertIn(sheet, workbook.sheetnames)
        asset_sheet = workbook['asset_list']
        data_rows = sum(
            1 for r in range(2, asset_sheet.max_row + 1)
            if asset_sheet.cell(row=r, column=6).value  # SN column F
        )
        self.assertGreater(data_rows, 5)
        self.assertEqual(data_rows, inspection.devices.count())


class ReportGoldenParityTests(TestCase):
    """Authoritative parity: reconstruct devices from a REAL EUS-generated report and
    assert our ported transforms reproduce its cover_page counts and categories.

    Skips when no golden report is available locally (e.g. CI). Set
    INSPECTION_GOLDEN_REPORT to point at a specific '... Report Per Store.xlsx'.
    """

    # Cover labels fed by devices that the EUS pipeline filters OUT of asset_list
    # (network gear + cash drawers), so they cannot be reconstructed from it.
    NON_ASSET_LIST_LABELS = {'Patch Panel', 'Router', 'Switch', 'AP', 'Cashdrawer'}

    def _find_golden(self):
        import glob
        override = os.environ.get('INSPECTION_GOLDEN_REPORT')
        if override and os.path.exists(override):
            return override
        pattern = (r'c:\Users\sean_\Documents\EUS_Device_Inspec\DeviceInspecFeishuAutomation'
                   r'\*\* Report Per Store.xlsx')
        matches = sorted(glob.glob(pattern))
        return matches[0] if matches else None

    def _read_golden(self, path):
        wb = load_workbook(path, data_only=True)
        al = wb['asset_list']
        header = {}
        for col in range(1, al.max_column + 1):
            value = al.cell(row=1, column=col).value
            if value:
                header[str(value).strip()] = col
        rows = []
        for r in range(2, al.max_row + 1):
            get = lambda name: al.cell(row=r, column=header[name]).value if name in header else None
            if all(get(n) in (None, '') for n in ('Category', 'SN', 'Asset ID')):
                continue
            rows.append({
                'category': get('Category'), 'brand_model': get('Brand-Model'),
                'sn': get('SN'), 'usage': get('Usage'), 'status': get('Status'),
            })
        cp = wb['cover_page']
        counts = {}
        for r in range(1, cp.max_row + 1):
            label = cp.cell(row=r, column=2).value
            if label is None:
                continue
            label = ' '.join(str(label).split())
            if label in COVER_PAGE_DEVICE_LABELS:
                value = cp.cell(row=r, column=4).value
                counts[label] = value if isinstance(value, int) else 0
        return rows, counts

    def test_cover_counts_match_golden(self):
        from types import SimpleNamespace
        from django.utils import timezone
        from inspections.constants import normalize_device_category

        golden = self._find_golden()
        if not golden:
            self.skipTest('No local EUS golden report available')
        rows, golden_counts = self._read_golden(golden)
        self.assertTrue(rows, 'golden asset_list had no rows')

        now = timezone.now()
        devices = []
        for row in rows:
            in_store = str(row['status'] or '').strip().lower() == 'in store'
            devices.append(SimpleNamespace(
                category=normalize_device_category(row['category']),
                usage=row['usage'] or '', brand_model=row['brand_model'] or '',
                status='in_store' if in_store else 'not_in_store',
                collected_at=now if in_store else None, is_new_device=False,
            ))

        computed = transforms.build_cover_page_summary_counts(devices)
        mismatches = {}
        for label in COVER_PAGE_DEVICE_LABELS:
            if label in self.NON_ASSET_LIST_LABELS:
                continue
            expected = golden_counts.get(label, 0)
            if computed.get(label, 0) != expected:
                mismatches[label] = {'golden': expected, 'computed': computed.get(label, 0)}
        self.assertEqual(mismatches, {}, f'cover_page count parity mismatch vs {os.path.basename(golden)}')
        # Sanity: the golden actually exercised the classifier (non-trivial data).
        self.assertGreater(sum(golden_counts.values()), 0)

    def test_category_normalization_is_idempotent_on_golden(self):
        from inspections.constants import normalize_device_category

        golden = self._find_golden()
        if not golden:
            self.skipTest('No local EUS golden report available')
        rows, _ = self._read_golden(golden)
        for row in rows:
            category = row['category']
            if category:
                # Golden categories are already canonical; normalizing must be a no-op.
                self.assertEqual(normalize_device_category(category), str(category).strip())
