# Generated by Django 5.2.3 on 2025-07-07 05:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for the report template', max_length=200, verbose_name='Template Name')),
                ('code', models.CharField(help_text='Unique code for programmatic reference', max_length=50, unique=True, verbose_name='Template Code')),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this report contains', verbose_name='Description')),
                ('report_type', models.CharField(choices=[('asset_inventory', 'Asset Inventory'), ('asset_valuation', 'Asset Valuation'), ('assignment_history', 'Assignment History'), ('audit_summary', 'Audit Summary'), ('depreciation', 'Depreciation Report'), ('warranty_expiry', 'Warranty Expiry'), ('utilization', 'Asset Utilization'), ('cost_analysis', 'Cost Analysis'), ('compliance', 'Compliance Report'), ('custom', 'Custom Report')], max_length=20, verbose_name='Report Type')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=10, verbose_name='Default Output Format')),
                ('template_definition', models.JSONField(default=dict, help_text='JSON configuration defining report structure, filters, and formatting', verbose_name='Template Definition')),
                ('default_filters', models.JSONField(blank=True, default=dict, help_text='Default filter values for this template', verbose_name='Default Filters')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this template is available to all users', verbose_name='Is Public')),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text='List of user roles that can use this template', verbose_name='Allowed Roles')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use', verbose_name='Is Active')),
                ('requires_approval', models.BooleanField(default=False, help_text='Whether reports from this template require approval before access', verbose_name='Requires Approval')),
                ('can_be_scheduled', models.BooleanField(default=True, help_text='Whether this report can be scheduled for automatic generation', verbose_name='Can Be Scheduled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this schedule', max_length=200, verbose_name='Schedule Name')),
                ('description', models.TextField(blank=True, help_text='Description of what this schedule generates', verbose_name='Description')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, verbose_name='Frequency')),
                ('start_date', models.DateField(help_text='When the schedule should start', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='When the schedule should end (optional)', null=True, verbose_name='End Date')),
                ('next_run', models.DateTimeField(blank=True, help_text='When the next report should be generated', null=True, verbose_name='Next Run')),
                ('last_run', models.DateTimeField(blank=True, help_text='When the last report was generated', null=True, verbose_name='Last Run')),
                ('filters', models.JSONField(default=dict, help_text='Default filters to apply to scheduled reports', verbose_name='Filters')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], max_length=10, verbose_name='Output Format')),
                ('email_recipients', models.JSONField(blank=True, default=list, help_text='Email addresses to send generated reports to', verbose_name='Email Recipients')),
                ('email_subject', models.CharField(blank=True, help_text='Subject line for scheduled report emails', max_length=200, verbose_name='Email Subject')),
                ('email_body', models.TextField(blank=True, help_text='Body text for scheduled report emails', verbose_name='Email Body')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active', verbose_name='Is Active')),
                ('consecutive_failures', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed generation attempts', verbose_name='Consecutive Failures')),
                ('max_failures', models.PositiveIntegerField(default=3, help_text='Maximum failures before schedule is paused', verbose_name='Max Failures')),
                ('last_error', models.TextField(blank=True, help_text='Last error message from failed generation', verbose_name='Last Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate', verbose_name='Report Template')),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_number', models.CharField(help_text='Unique identifier for this generated report', max_length=50, unique=True, verbose_name='Report Number')),
                ('name', models.CharField(help_text='Descriptive name for this report instance', max_length=200, verbose_name='Report Name')),
                ('filters_applied', models.JSONField(default=dict, help_text='Filters and parameters used to generate this report', verbose_name='Filters Applied')),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], max_length=10, verbose_name='Output Format')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('generation_method', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('api', 'API'), ('batch', 'Batch')], default='manual', max_length=20, verbose_name='Generation Method')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('file_path', models.CharField(blank=True, help_text='Path to the generated report file', max_length=500, verbose_name='File Path')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size of the generated file in bytes', null=True, verbose_name='File Size')),
                ('record_count', models.PositiveIntegerField(blank=True, help_text='Number of records included in the report', null=True, verbose_name='Record Count')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this report is accessible to all users in the company', verbose_name='Is Public')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requires Approval')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('error_message', models.TextField(blank=True, help_text='Error message if report generation failed', verbose_name='Error Message')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this report will be automatically deleted', null=True, verbose_name='Expires At')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this report', verbose_name='Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.company', verbose_name='Company')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reports', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Users who have access to this report', related_name='accessible_reports', to=settings.AUTH_USER_MODEL, verbose_name='Shared With')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to='reports.reporttemplate', verbose_name='Report Template')),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_type', models.CharField(choices=[('view', 'View Only'), ('download', 'View and Download'), ('full', 'Full Access')], default='view', max_length=20, verbose_name='Share Type')),
                ('can_reshare', models.BooleanField(default=False, help_text='Whether the recipient can share this report with others', verbose_name='Can Reshare')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this share expires (optional)', null=True, verbose_name='Expires At')),
                ('shared_at', models.DateTimeField(auto_now_add=True, verbose_name='Shared At')),
                ('accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='First Accessed At')),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this share has been accessed', verbose_name='Access Count')),
                ('notes', models.TextField(blank=True, help_text='Notes about this share', verbose_name='Notes')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='reports.generatedreport', verbose_name='Report')),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_shared_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Shared By')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_shares', to=settings.AUTH_USER_MODEL, verbose_name='Shared With')),
            ],
            options={
                'verbose_name': 'Report Share',
                'verbose_name_plural': 'Report Shares',
                'ordering': ['-shared_at'],
                'unique_together': {('report', 'shared_with')},
            },
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['company', '-requested_at'], name='reports_gen_company_7c405c_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['requested_by', '-requested_at'], name='reports_gen_request_1c15cf_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['status', '-requested_at'], name='reports_gen_status_c6b051_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['template', '-requested_at'], name='reports_gen_templat_0b54b9_idx'),
        ),
    ]
