# Generated by Django 5.2.8 on 2026-04-15 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_make_division_code_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(help_text='Primary contact person name', max_length=200, verbose_name='Contact Person')),
                ('phone', models.CharField(help_text='Primary contact phone number', max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254, verbose_name='Email')),
                ('delivery_address', models.TextField(help_text='Detailed delivery address', verbose_name='Delivery Address')),
                ('delivery_city', models.CharField(max_length=100, verbose_name='Delivery City')),
                ('delivery_contact', models.CharField(help_text='Name of person to receive delivery', max_length=200, verbose_name='Delivery Contact Name')),
                ('delivery_phone', models.CharField(help_text='Phone number for delivery contact', max_length=20, verbose_name='Delivery Phone')),
                ('delivery_method', models.CharField(choices=[('self_pickup', 'Self Pickup'), ('delivery', 'Delivery'), ('courier', 'Courier'), ('express', 'Express')], default='delivery', max_length=20, verbose_name='Delivery Method')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50, verbose_name='Tax ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='companies.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
    ]
