# Generated by Django 5.2.8 on 2026-04-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('quotations', '0002_remove_quotation_customer_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
