# Generated by Django 5.2.3 on 2025-07-07 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('companies', '0002_location'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_number', models.CharField(help_text='Unique identifier for this audit session', max_length=50, unique=True, verbose_name='Audit Number')),
                ('name', models.CharField(help_text='Descriptive name for this audit', max_length=200, verbose_name='Audit Name')),
                ('description', models.TextField(blank=True, help_text='Purpose and scope of this audit', verbose_name='Description')),
                ('audit_type', models.CharField(choices=[('scheduled', 'Scheduled Audit'), ('spot_check', 'Spot Check'), ('annual', 'Annual Audit'), ('inventory', 'Full Inventory'), ('compliance', 'Compliance Audit')], default='scheduled', max_length=20, verbose_name='Audit Type')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20, verbose_name='Status')),
                ('planned_start_date', models.DateField(verbose_name='Planned Start Date')),
                ('planned_end_date', models.DateField(verbose_name='Planned End Date')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start Date')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual End Date')),
                ('total_assets_expected', models.PositiveIntegerField(default=0, help_text='Expected number of assets to audit', verbose_name='Total Assets Expected')),
                ('total_assets_found', models.PositiveIntegerField(default=0, help_text='Number of assets successfully located and verified', verbose_name='Total Assets Found')),
                ('total_assets_missing', models.PositiveIntegerField(default=0, help_text='Number of assets that could not be located', verbose_name='Total Assets Missing')),
                ('total_discrepancies', models.PositiveIntegerField(default=0, help_text='Number of assets with information discrepancies', verbose_name='Total Discrepancies')),
                ('notes', models.TextField(blank=True, help_text='General notes about this audit', verbose_name='Notes')),
                ('report_generated', models.BooleanField(default=False, help_text='Whether the audit report has been generated', verbose_name='Report Generated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('auditors', models.ManyToManyField(help_text='Users who can perform audits in this session', related_name='audits', to=settings.AUTH_USER_MODEL, verbose_name='Auditors')),
                ('categories', models.ManyToManyField(blank=True, help_text='Specific asset categories to audit (all if none selected)', related_name='audits', to='assets.assetcategory', verbose_name='Categories')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audits', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('divisions', models.ManyToManyField(blank=True, help_text='Specific divisions to audit (all if none selected)', related_name='audits', to='companies.division', verbose_name='Divisions')),
                ('locations', models.ManyToManyField(blank=True, help_text='Specific locations to audit (all if none selected)', related_name='audits', to='companies.location', verbose_name='Locations')),
                ('primary_auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_audits', to=settings.AUTH_USER_MODEL, verbose_name='Primary Auditor')),
            ],
            options={
                'verbose_name': 'Asset Audit',
                'verbose_name_plural': 'Asset Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Failed Login'), ('assign', 'Assign Asset'), ('return', 'Return Asset'), ('audit', 'Asset Audit'), ('export', 'Data Export'), ('import', 'Data Import'), ('access', 'Access Resource'), ('permission_change', 'Permission Change'), ('password_change', 'Password Change'), ('settings_change', 'Settings Change')], help_text='Type of action performed', max_length=20, verbose_name='Action')),
                ('object_id', models.CharField(blank=True, max_length=255, verbose_name='Object ID')),
                ('description', models.TextField(help_text='Human-readable description of what happened', verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data about the action (before/after values, etc.)', verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred', verbose_name='Timestamp')),
                ('company', models.ForeignKey(blank=True, help_text='Company context for the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='companies.company', verbose_name='Company')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text='Name of the field that was changed', max_length=100, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, help_text='Previous value of the field', verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, help_text='New value of the field', verbose_name='New Value')),
                ('field_type', models.CharField(blank=True, help_text='Data type of the field (for proper display)', max_length=50, verbose_name='Field Type')),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='audit.auditlog', verbose_name='Audit Log')),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'ordering': ['field_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='Type of system event', max_length=100, verbose_name='Event Type')),
                ('category', models.CharField(choices=[('security', 'Security'), ('performance', 'Performance'), ('error', 'Error'), ('maintenance', 'Maintenance'), ('backup', 'Backup'), ('integration', 'Integration')], max_length=20, verbose_name='Category')),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='Severity Level')),
                ('message', models.TextField(help_text='Detailed message about the event', verbose_name='Message')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event data and context', verbose_name='Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('resolved', models.BooleanField(default=False, help_text='Whether this event has been resolved', verbose_name='Resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the event was resolved', verbose_name='Resolution Notes')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_system_events', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'System Event',
                'verbose_name_plural': 'System Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssetAuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('found', 'Found'), ('missing', 'Missing'), ('discrepancy', 'Discrepancy'), ('damaged', 'Damaged'), ('unauthorized', 'Unauthorized Asset')], max_length=20, verbose_name='Verification Status')),
                ('physical_location_verified', models.BooleanField(default=False, help_text='Asset found in expected location', verbose_name='Physical Location Verified')),
                ('actual_location', models.CharField(blank=True, help_text='Where the asset was actually found (if different)', max_length=500, verbose_name='Actual Location')),
                ('condition_at_audit', models.CharField(blank=True, choices=[], max_length=20, verbose_name='Condition at Audit')),
                ('condition_notes', models.TextField(blank=True, help_text='Detailed notes about asset condition', verbose_name='Condition Notes')),
                ('serial_number_verified', models.BooleanField(default=False, help_text='Serial number matches system records', verbose_name='Serial Number Verified')),
                ('actual_serial_number', models.CharField(blank=True, help_text='Serial number found on asset (if different)', max_length=100, verbose_name='Actual Serial Number')),
                ('verification_photo', models.ImageField(blank=True, help_text='Photo taken during audit for verification', null=True, upload_to='audit/photos/', verbose_name='Verification Photo')),
                ('serial_number_photo', models.ImageField(blank=True, help_text='Close-up photo of asset serial number', null=True, upload_to='audit/serial_numbers/', verbose_name='Serial Number Photo')),
                ('audited_at', models.DateTimeField(auto_now_add=True, verbose_name='Audited At')),
                ('notes', models.TextField(blank=True, help_text='Detailed notes about this asset verification', verbose_name='Audit Notes')),
                ('discrepancies', models.JSONField(blank=True, default=dict, help_text='Detailed list of any discrepancies found', verbose_name='Discrepancies')),
                ('requires_follow_up', models.BooleanField(default=False, help_text='Whether this record requires follow-up action', verbose_name='Requires Follow-up')),
                ('follow_up_completed', models.BooleanField(default=False, verbose_name='Follow-up Completed')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='assets.asset', verbose_name='Asset')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='audit.assetaudit', verbose_name='Audit')),
                ('audited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_records', to=settings.AUTH_USER_MODEL, verbose_name='Audited By')),
                ('follow_up_assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_follow_ups', to=settings.AUTH_USER_MODEL, verbose_name='Follow-up Assigned To')),
            ],
            options={
                'verbose_name': 'Asset Audit Record',
                'verbose_name_plural': 'Asset Audit Records',
                'ordering': ['audited_at'],
                'unique_together': {('audit', 'asset')},
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', '-timestamp'], name='audit_audit_company_853041_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['severity', '-timestamp'], name='audit_syste_severit_c089e4_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['category', '-timestamp'], name='audit_syste_categor_376274_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['resolved', '-timestamp'], name='audit_syste_resolve_90e025_idx'),
        ),
    ]
