# Generated by Django 5.2.3 on 2025-07-07 05:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the company', max_length=200, unique=True, verbose_name='Company Name')),
                ('code', models.CharField(help_text='Unique identifier code for the company (used in asset numbering)', max_length=20, unique=True, verbose_name='Company Code')),
                ('description', models.TextField(blank=True, help_text='Brief description of the company', verbose_name='Description')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='Company contact email', max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, help_text='Company website URL', verbose_name='Website')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', help_text='Current status of the company', max_length=20, verbose_name='Status')),
                ('logo', models.ImageField(blank=True, help_text='Upload company logo (optional)', null=True, upload_to='companies/logos/', verbose_name='Company Logo')),
                ('asset_prefix', models.CharField(blank=True, help_text='Prefix used for asset numbering (e.g., "COMP-")', max_length=10, verbose_name='Asset Prefix')),
                ('next_asset_number', models.PositiveIntegerField(default=1, help_text='Next number to be used for asset numbering', verbose_name='Next Asset Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the division or department', max_length=200, verbose_name='Division Name')),
                ('code', models.CharField(help_text='Unique identifier code for the division within the company', max_length=20, verbose_name='Division Code')),
                ('description', models.TextField(blank=True, help_text='Brief description of the division', verbose_name='Description')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='Division contact email', max_length=254, verbose_name='Email')),
                ('location', models.CharField(blank=True, help_text='Physical location of the division', max_length=200, verbose_name='Location')),
                ('building', models.CharField(blank=True, help_text='Building name or number', max_length=100, verbose_name='Building')),
                ('floor', models.CharField(blank=True, help_text='Floor number or name', max_length=50, verbose_name='Floor')),
                ('room', models.CharField(blank=True, help_text='Room number or name', max_length=50, verbose_name='Room')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('merged', 'Merged')], default='active', help_text='Current status of the division', max_length=20, verbose_name='Status')),
                ('budget_code', models.CharField(blank=True, help_text='Budget or cost center code for this division', max_length=50, verbose_name='Budget Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(help_text='Company this division belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='companies.company', verbose_name='Company')),
                ('manager', models.ForeignKey(blank=True, help_text='User responsible for managing this division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_divisions', to=settings.AUTH_USER_MODEL, verbose_name='Division Manager')),
                ('parent_division', models.ForeignKey(blank=True, help_text='Parent division if this is a sub-division', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='companies.division', verbose_name='Parent Division')),
            ],
        ),
    ]
