# Generated by Django 5.2.3 on 2025-07-05 09:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official name of the company', max_length=200, unique=True, verbose_name='Company Name')),
                ('code', models.CharField(help_text='Short code used for asset numbering (e.g., ACME, TECH)', max_length=10, unique=True, verbose_name='Company Code')),
                ('email', models.EmailField(blank=True, help_text='Main contact email for the company', max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('asset_numbering_type', models.CharField(choices=[('continuity', 'Continuity (ACME-1, ACME-2, ...)'), ('prefix_sn', 'Prefix + Serial Number (ACME-SN123456)'), ('custom', 'Custom (Manual input)')], default='continuity', help_text='How asset numbers should be generated for this company', max_length=20, verbose_name='Asset Numbering Type')),
                ('asset_prefix', models.CharField(blank=True, help_text='Prefix used for asset numbering (e.g., ACME, TECH)', max_length=10, verbose_name='Asset Prefix')),
                ('next_asset_number', models.PositiveIntegerField(default=1, help_text='Next number to use for continuity-based asset numbering', verbose_name='Next Asset Number')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this company is active in the system', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the division or department', max_length=200, verbose_name='Division Name')),
                ('code', models.CharField(help_text='Short code for the division (e.g., IT, HR, FIN)', max_length=10, verbose_name='Division Code')),
                ('description', models.TextField(blank=True, help_text='Description of the division and its responsibilities', verbose_name='Description')),
                ('location', models.CharField(blank=True, help_text='Physical location of this division', max_length=255, verbose_name='Location')),
                ('cost_center', models.CharField(blank=True, help_text='Cost center code for financial tracking', max_length=50, verbose_name='Cost Center')),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Annual budget limit for asset purchases', max_digits=12, null=True, verbose_name='Budget Limit')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this division is active in the system', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='companies.company', verbose_name='Company')),
                ('manager', models.ForeignKey(blank=True, help_text='User responsible for managing this division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_divisions', to=settings.AUTH_USER_MODEL, verbose_name='Division Manager')),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['company__name', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the location (e.g., Building A, Floor 2, Room 201)', max_length=200, verbose_name='Location Name')),
                ('code', models.CharField(help_text='Short code for the location (e.g., B1-F2-R201)', max_length=20, verbose_name='Location Code')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the location', verbose_name='Description')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('location_type', models.CharField(choices=[('office', 'Office'), ('warehouse', 'Warehouse'), ('factory', 'Factory'), ('retail', 'Retail Store'), ('remote', 'Remote Location'), ('other', 'Other')], default='office', max_length=20, verbose_name='Location Type')),
                ('contact_person', models.CharField(blank=True, help_text='Person responsible for this location', max_length=200, verbose_name='Contact Person')),
                ('contact_phone', models.CharField(blank=True, max_length=17, verbose_name='Contact Phone')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location is active for asset assignment', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companies.company', verbose_name='Company')),
                ('division', models.ForeignKey(blank=True, help_text='Division this location belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companies.division', verbose_name='Division')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['company__name', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
