# Generated by Django 5.2.3 on 2025-07-07 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the location', max_length=200, verbose_name='Location Name')),
                ('code', models.CharField(help_text='Unique code for the location (e.g., B1-F3-R101)', max_length=50, verbose_name='Location Code')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the location', verbose_name='Description')),
                ('location_type', models.CharField(choices=[('building', 'Building'), ('floor', 'Floor'), ('room', 'Room'), ('warehouse', 'Warehouse'), ('office', 'Office'), ('factory', 'Factory'), ('other', 'Other')], default='room', max_length=20, verbose_name='Location Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20, verbose_name='Status')),
                ('area_size', models.DecimalField(blank=True, decimal_places=2, help_text='Size of the location in square meters', max_digits=10, null=True, verbose_name='Area Size (sq meters)')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum capacity (people, assets, etc.)', null=True, verbose_name='Capacity')),
                ('address_line1', models.CharField(blank=True, max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state_province', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('phone_number', models.CharField(blank=True, max_length=17, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate', max_digits=9, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companies.company', verbose_name='Company')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companies.division', verbose_name='Division')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to=settings.AUTH_USER_MODEL, verbose_name='Location Manager')),
                ('parent_location', models.ForeignKey(blank=True, help_text='Parent location in hierarchy (e.g., floor for room)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_locations', to='companies.location', verbose_name='Parent Location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
