# Generated by Django 5.2.3 on 2025-07-06 15:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='company',
            name='asset_numbering_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the company', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload company logo (optional)', null=True, upload_to='companies/logos/', verbose_name='Company Logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', help_text='Current status of the company', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Company website URL', verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='division',
            name='budget_code',
            field=models.CharField(blank=True, help_text='Budget or cost center code for this division', max_length=50, verbose_name='Budget Code'),
        ),
        migrations.AddField(
            model_name='division',
            name='building',
            field=models.CharField(blank=True, help_text='Building name or number', max_length=100, verbose_name='Building'),
        ),
        migrations.AddField(
            model_name='division',
            name='email',
            field=models.EmailField(blank=True, help_text='Division contact email', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='division',
            name='floor',
            field=models.CharField(blank=True, help_text='Floor number or name', max_length=50, verbose_name='Floor'),
        ),
        migrations.AddField(
            model_name='division',
            name='parent_division',
            field=models.ForeignKey(blank=True, help_text='Parent division if this is a sub-division', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='companies.division', verbose_name='Parent Division'),
        ),
        migrations.AddField(
            model_name='division',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='division',
            name='room',
            field=models.CharField(blank=True, help_text='Room number or name', max_length=50, verbose_name='Room'),
        ),
        migrations.AddField(
            model_name='division',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('merged', 'Merged')], default='active', help_text='Current status of the division', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='company',
            name='asset_prefix',
            field=models.CharField(blank=True, help_text='Prefix used for asset numbering (e.g., "COMP-")', max_length=10, verbose_name='Asset Prefix'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(help_text='Unique identifier code for the company (used in asset numbering)', max_length=20, unique=True, verbose_name='Company Code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='Company contact email', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='next_asset_number',
            field=models.PositiveIntegerField(default=1, help_text='Next number to be used for asset numbering', verbose_name='Next Asset Number'),
        ),
        migrations.AlterField(
            model_name='division',
            name='code',
            field=models.CharField(help_text='Unique identifier code for the division within the company', max_length=20, verbose_name='Division Code'),
        ),
        migrations.AlterField(
            model_name='division',
            name='company',
            field=models.ForeignKey(help_text='Company this division belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='companies.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='division',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the division', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='division',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='division',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location of the division', max_length=200, verbose_name='Location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='division',
            name='budget_limit',
        ),
        migrations.RemoveField(
            model_name='division',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='division',
            name='is_active',
        ),
    ]
