# Generated by Django 5.2.3 on 2025-07-07 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('admin', 'Company Admin'), ('viewer', 'Viewer')], default='employee', help_text='User role within the company', max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Status')),
                ('employee_id', models.CharField(blank=True, help_text='Company employee identification number', max_length=50, verbose_name='Employee ID')),
                ('department', models.CharField(blank=True, help_text='Department or team within the company', max_length=100, verbose_name='Department')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Job Title')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Hire Date')),
                ('start_date', models.DateField(auto_now_add=True, help_text='Date when user joined this company in the system', verbose_name='Company Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Date when user left the company', null=True, verbose_name='End Date')),
                ('work_phone', models.CharField(blank=True, max_length=20, verbose_name='Work Phone')),
                ('work_email', models.EmailField(blank=True, help_text='Company email address if different from user email', max_length=254, verbose_name='Work Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='companies.company', verbose_name='Company')),
                ('division', models.ForeignKey(blank=True, help_text='Primary division for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_users', to='companies.division', verbose_name='Division')),
                ('location', models.ForeignKey(blank=True, help_text='Primary work location for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_users', to='companies.location', verbose_name='Primary Location')),
                ('manager', models.ForeignKey(blank=True, help_text='Direct manager for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='companies.companyuser', verbose_name='Manager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Company User',
                'verbose_name_plural': 'Company Users',
                'ordering': ['company__name', 'user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['company', 'status'], name='companies_c_company_66ac46_idx'), models.Index(fields=['user', 'status'], name='companies_c_user_id_e54036_idx'), models.Index(fields=['employee_id'], name='companies_c_employe_353fe2_idx')],
                'unique_together': {('user', 'company')},
            },
        ),
    ]
