# Generated by Django 5.2.3 on 2025-07-07 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='User responsible for managing this division', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_manager_for', to=settings.AUTH_USER_MODEL, verbose_name='Division Manager'),
        ),
        migrations.AlterField(
            model_name='location',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_manager_for', to=settings.AUTH_USER_MODEL, verbose_name='Location Manager'),
        ),
    ]
