# Generated by Django 5.2 on 2025-08-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_division_manager_alter_location_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the location (e.g., B1-F3-R101)', max_length=50, verbose_name='Location Code'),
        ),
    ]
