# Generated by Django 5.2 on 2025-08-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_make_location_code_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='code',
            field=models.CharField(blank=True, help_text='Unique identifier code for the division within the company (optional)', max_length=20, verbose_name='Division Code'),
        ),
    ]
