# Generated by Django 5.2.8 on 2026-04-16 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_make_division_code_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='primary_contact_company_user',
            field=models.ForeignKey(blank=True, help_text='Primary business contact selected from company users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_contact_for_companies', to='companies.companyuser', verbose_name='Primary Contact'),
        ),
    ]
