# Generated by Django 5.2.8 on 2026-04-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_primary_contact_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rack',
            field=models.CharField(blank=True, help_text='Optional rack identifier', max_length=50, null=True, verbose_name='Rack'),
        ),
        migrations.AddField(
            model_name='location',
            name='shelf',
            field=models.CharField(blank=True, help_text='Optional shelf identifier', max_length=50, null=True, verbose_name='Shelf'),
        ),
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.CharField(blank=True, help_text='Optional zone identifier', max_length=50, null=True, verbose_name='Zone'),
        ),
    ]
