# Generated by Django 5.2.8 on 2026-04-20 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_location_rack_location_shelf_location_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuser',
            options={'ordering': ['company__name', 'name', 'user__last_name', 'user__first_name'], 'verbose_name': 'Company Contact', 'verbose_name_plural': 'Company Contacts'},
        ),
        migrations.AddField(
            model_name='companyuser',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Primary contact/recipient name', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Linked User'),
        ),
    ]
