# Generated by Django 5.2.8 on 2026-04-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_companyuser_options_companyuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='chinese_address',
            field=models.TextField(blank=True, verbose_name='Chinese Address'),
        ),
        migrations.AddField(
            model_name='location',
            name='code_2',
            field=models.CharField(blank=True, help_text='Secondary code for the location (optional)', max_length=50, verbose_name='Location Code 2'),
        ),
        migrations.AddField(
            model_name='location',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_contacts', to='companies.companyuser', verbose_name='Location Contact'),
        ),
        migrations.AddField(
            model_name='location',
            name='name_en',
            field=models.CharField(blank=True, help_text='English name of the location', max_length=200, verbose_name='Location Name (English)'),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the location (e.g., B1-F3-R101)', max_length=50, null=True, verbose_name='Location Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('office', 'Office'), ('store', 'Store'), ('other', 'Other')], default='other', max_length=20, verbose_name='Location Type'),
        ),
        migrations.AlterField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('under_construction', 'Under Construction')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
