# Generated by Django 5.2.8 on 2026-04-21 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_migrate_location_legacy_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, verbose_name='Module')),
                ('import_type', models.CharField(max_length=50, verbose_name='Import Type')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='completed', max_length=20, verbose_name='Status')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Total Rows')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='Created Count')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='Updated Count')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='Skipped Count')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Error Count')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True, verbose_name='Rolled Back At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_runs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Import Run',
                'verbose_name_plural': 'Import Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRunChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='Sequence')),
                ('row_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Source Row')),
                ('app_label', models.CharField(max_length=100, verbose_name='App Label')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('object_pk', models.CharField(max_length=64, verbose_name='Object PK')),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update')], max_length=20, verbose_name='Operation')),
                ('before_data', models.JSONField(blank=True, default=dict, verbose_name='Before Data')),
                ('after_data', models.JSONField(blank=True, default=dict, verbose_name='After Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='companies.importrun', verbose_name='Import Run')),
            ],
            options={
                'verbose_name': 'Import Run Change',
                'verbose_name_plural': 'Import Run Changes',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='importrun',
            index=models.Index(fields=['user', 'module', 'import_type', 'created_at'], name='companies_i_user_id_86ad67_idx'),
        ),
        migrations.AddIndex(
            model_name='importrun',
            index=models.Index(fields=['module', 'import_type', 'created_at'], name='companies_i_module_aa1a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='importrun',
            index=models.Index(fields=['status', 'rolled_back_at'], name='companies_i_status_a11456_idx'),
        ),
        migrations.AddIndex(
            model_name='importrunchange',
            index=models.Index(fields=['run', 'sequence'], name='companies_i_run_id_e3b755_idx'),
        ),
        migrations.AddIndex(
            model_name='importrunchange',
            index=models.Index(fields=['app_label', 'model_name', 'object_pk'], name='companies_i_app_lab_978851_idx'),
        ),
    ]
