# Generated by Django 5.2.8 on 2026-04-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_importrun_importrunchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='is_authorized_rfq_sender',
            field=models.BooleanField(default=False, help_text='Only authorized contacts can trigger quotation auto-generation from RFQ emails.', verbose_name='Authorized RFQ Sender'),
        ),
    ]
