# Generated by Django 5.2.8 on 2026-09-07 14:30

import django.db.models.deletion
import inspections.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0014_assetcategory_item_type'),
        ('companies', '0014_company_default_quotation_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_device_uid', models.CharField(blank=True, help_text='Idempotency key from the mini program; auto-filled when absent.', max_length=64, verbose_name='Client Device UID')),
                ('row_order', models.PositiveIntegerField(default=0, verbose_name='Row Order')),
                ('asset_id_text', models.CharField(blank=True, max_length=100, verbose_name='Asset ID')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Category')),
                ('brand_model', models.CharField(blank=True, max_length=200, verbose_name='Brand-Model')),
                ('sn', models.CharField(blank=True, max_length=100, verbose_name='Serial Number')),
                ('usage', models.CharField(blank=True, max_length=50, verbose_name='Usage')),
                ('warranty_start', models.DateField(blank=True, null=True, verbose_name='Warranty Start')),
                ('photo_required', models.BooleanField(default=True, verbose_name='Photo Required')),
                ('outline', models.CharField(blank=True, max_length=100, verbose_name='Outline')),
                ('device_notes', models.CharField(blank=True, max_length=255, verbose_name='Device Notes')),
                ('status', models.CharField(choices=[('in_store', 'In Store'), ('not_in_store', 'Not In Store'), ('new', 'New')], default='in_store', max_length=20, verbose_name='Status')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP Address')),
                ('cpu', models.CharField(blank=True, max_length=100, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=100, verbose_name='Memory')),
                ('hdd', models.CharField(blank=True, max_length=100, verbose_name='HDD')),
                ('windows_version', models.CharField(blank=True, max_length=100, verbose_name='Windows Version')),
                ('ios_version', models.CharField(blank=True, max_length=100, verbose_name='iOS Version')),
                ('drive_c_free_space', models.CharField(blank=True, max_length=50, verbose_name='Drive C Free Space')),
                ('intact_asset_tag', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Intact Asset Tag')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('is_new_device', models.BooleanField(default=False, verbose_name='New Device')),
                ('collected_at', models.DateTimeField(blank=True, null=True, verbose_name='Collected At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_devices', to='assets.asset', verbose_name='Linked Asset')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_inspection_devices', to=settings.AUTH_USER_MODEL, verbose_name='Collected By')),
            ],
            options={
                'verbose_name': 'Inspection Device',
                'verbose_name_plural': 'Inspection Devices',
                'ordering': ['row_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jda_code', models.CharField(blank=True, max_length=20, verbose_name='Store JDA Code')),
                ('brand_name', models.CharField(blank=True, max_length=100, verbose_name='Brand')),
                ('store_name', models.CharField(blank=True, max_length=100, verbose_name='Store Name')),
                ('store_label', models.CharField(blank=True, help_text='Full label used on reports, e.g. "22149 Gucci SZOL".', max_length=200, verbose_name='Store Label')),
                ('inspection_date', models.DateField(verbose_name='Inspection Date')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('submitted', 'Submitted')], default='planned', max_length=20, verbose_name='Status')),
                ('arriving_time', models.TimeField(blank=True, null=True, verbose_name='Arriving Time')),
                ('leaving_time', models.TimeField(blank=True, null=True, verbose_name='Leaving Time')),
                ('wifi_coverage', models.CharField(blank=True, choices=[('good', 'Good'), ('weak', 'Weak'), ('none', 'None')], max_length=10, verbose_name='WiFi Coverage')),
                ('error_setting_fixed_count', models.PositiveIntegerField(default=0, verbose_name='Error Setting Fixed')),
                ('store_issue_found_count', models.PositiveIntegerField(default=0, verbose_name='Store Issue Found')),
                ('issue_to_follow_count', models.PositiveIntegerField(default=0, verbose_name='Issue To Be Followed Up')),
                ('wifi_covers_store', models.BooleanField(blank=True, help_text='无线信号能覆盖整个店铺且信号较强 (是/否).', null=True, verbose_name='WiFi Covers Whole Store')),
                ('it_support_rating', models.CharField(blank=True, choices=[('satisfied', 'Satisfied'), ('normal', 'Normal'), ('unsatisfied', 'Unsatisfied')], max_length=20, verbose_name='IT Support Service Rating')),
                ('it_support_comment', models.TextField(blank=True, verbose_name='IT Support Comment')),
                ('device_counts', models.JSONField(blank=True, default=dict, help_text='Engineer-confirmed counts keyed by confirmation_page label.', verbose_name='Confirmation Device Counts')),
                ('cover_extras', models.JSONField(blank=True, default=dict, help_text='WiFi SSID, Redwood/store-WiFi flags, rack size, music/ShopperTrak, etc.', verbose_name='Cover Page Extras')),
                ('store_signature', models.ImageField(blank=True, null=True, upload_to=inspections.models.inspection_signature_upload_path, verbose_name='Store Signature')),
                ('engineer_signature', models.ImageField(blank=True, null=True, upload_to=inspections.models.inspection_signature_upload_path, verbose_name='Engineer Signature')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Signed At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('report_file', models.FileField(blank=True, null=True, upload_to=inspections.models.inspection_report_upload_path, verbose_name='Report Workbook')),
                ('photo_zip', models.FileField(blank=True, null=True, upload_to=inspections.models.inspection_photo_zip_upload_path, verbose_name='Photo Archive')),
                ('report_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Report Generated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_inspections', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_inspections', to='companies.division', verbose_name='Brand / Division')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Onsite Engineer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_inspections', to='companies.location', verbose_name='Store / Location')),
            ],
            options={
                'verbose_name': 'Store Inspection',
                'verbose_name_plural': 'Store Inspections',
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('overall', 'Device Overall'), ('serial', 'Serial Number'), ('rack1', 'Rack 1'), ('rack2', 'Rack 2'), ('rack3', 'Rack 3'), ('router', 'Router'), ('switch', 'Switch'), ('patchpanel', 'Patch Panel'), ('speedtest_ethernet', 'Speedtest Ethernet'), ('speedtest_wifi', 'Speedtest WiFi'), ('issue', 'Issue'), ('cash_drawer', 'Cash Drawer')], max_length=20, verbose_name='Kind')),
                ('image', models.ImageField(upload_to=inspections.models.inspection_photo_upload_path, verbose_name='Image')),
                ('client_photo_uid', models.CharField(blank=True, help_text='Idempotency key from the mini program; auto-filled when absent.', max_length=64, verbose_name='Client Photo UID')),
                ('display_name', models.CharField(blank=True, help_text='Final business filename assigned at report time.', max_length=255, verbose_name='Display Name')),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Sort Index')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='Captured At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspectiondevice', verbose_name='Device')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_inspection_photos', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('store_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.storeinspection', verbose_name='Store Inspection')),
            ],
            options={
                'verbose_name': 'Inspection Photo',
                'verbose_name_plural': 'Inspection Photos',
                'ordering': ['sort_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField(default=0, verbose_name='Sequence')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('fixed', 'Fixed'), ('to_be_followed', 'To Be Followed')], default='to_be_followed', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='inspections.inspectionphoto', verbose_name='Photo')),
                ('store_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='inspections.storeinspection', verbose_name='Store Inspection')),
            ],
            options={
                'verbose_name': 'Inspection Issue',
                'verbose_name_plural': 'Inspection Issues',
                'ordering': ['seq', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='inspectiondevice',
            name='store_inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inspections.storeinspection', verbose_name='Store Inspection'),
        ),
        migrations.AddIndex(
            model_name='storeinspection',
            index=models.Index(fields=['engineer', 'status'], name='inspections_enginee_dcc244_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinspection',
            index=models.Index(fields=['location', 'inspection_date'], name='inspections_locatio_f449d8_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinspection',
            index=models.Index(fields=['jda_code'], name='inspections_jda_cod_226e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionphoto',
            index=models.Index(fields=['store_inspection', 'kind'], name='inspections_store_i_452ecb_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspectionphoto',
            constraint=models.UniqueConstraint(fields=('store_inspection', 'client_photo_uid'), name='uniq_inspection_photo_uid'),
        ),
        migrations.AddIndex(
            model_name='inspectiondevice',
            index=models.Index(fields=['store_inspection', 'category'], name='inspections_store_i_2d4838_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiondevice',
            index=models.Index(fields=['sn'], name='inspections_sn_6ba633_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspectiondevice',
            constraint=models.UniqueConstraint(fields=('store_inspection', 'client_device_uid'), name='uniq_inspection_device_uid'),
        ),
    ]
