# Generated by Django 5.2.8 on 2026-09-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiondevice',
            name='is_company_phone',
            field=models.BooleanField(default=False, verbose_name='Company Phone'),
        ),
        migrations.AddField(
            model_name='inspectiondevice',
            name='user_email',
            field=models.CharField(blank=True, help_text='Company-phone user; stored in email format.', max_length=100, verbose_name='User (Email)'),
        ),
    ]
