# Generated by Django 5.2.8 on 2026-09-21 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspectionbatch_storeinspection_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionSignoffLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(default='signoff', max_length=20, verbose_name='Operation')),
                ('description', models.TextField(verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('store_inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoff_logs', to='inspections.storeinspection', verbose_name='Store Inspection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_signoff_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Inspection Signoff Log',
                'verbose_name_plural': 'Inspection Signoff Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store_inspection', '-created_at'], name='inspections_store_i_5aaacc_idx')],
            },
        ),
    ]
