# Generated by Django 5.2.8 on 2026-09-20 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_company_default_quotation_template'),
        ('inspections', '0002_inspectiondevice_is_company_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Batch Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('brand', 'By Brand'), ('upload', 'Schedule Upload')], default='manual', max_length=20, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_batches', to='companies.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_batches', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_batches', to='companies.division', verbose_name='Brand / Division')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_batches', to=settings.AUTH_USER_MODEL, verbose_name='Primary Engineer')),
                ('import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_batches', to='companies.importrun', verbose_name='Import Run')),
            ],
            options={
                'verbose_name': 'Inspection Batch',
                'verbose_name_plural': 'Inspection Batches',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='storeinspection',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='inspections.inspectionbatch', verbose_name='Batch'),
        ),
        migrations.AddIndex(
            model_name='storeinspection',
            index=models.Index(fields=['batch', 'inspection_date'], name='inspections_batch_i_f30128_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionbatch',
            index=models.Index(fields=['company', '-start_date'], name='inspections_company_7a8899_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionbatch',
            index=models.Index(fields=['division', '-start_date'], name='inspections_divisio_d84e54_idx'),
        ),
    ]
