# Generated by Django 5.2.8 on 2026-09-23 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_company_default_quotation_template'),
        ('inspections', '0004_inspectionsignofflog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionWifiWeakPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_index', models.PositiveIntegerField(default=0, verbose_name='Sort Index')),
                ('location', models.CharField(max_length=120, verbose_name='Weak Point Location')),
                ('description', models.CharField(max_length=255, verbose_name='Issue Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'WiFi Weak Point',
                'verbose_name_plural': 'WiFi Weak Points',
                'ordering': ['sort_index', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='storeinspection',
            name='wifi_covers_store',
        ),
        migrations.AddField(
            model_name='storeinspection',
            name='slot',
            field=models.CharField(choices=[('am', 'Morning'), ('pm', 'Afternoon')], default='am', help_text='AM or PM batch within the inspection date.', max_length=2, verbose_name='Time Slot'),
        ),
        migrations.AlterField(
            model_name='inspectionissue',
            name='status',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('to_be_followed', 'To Be Followed'), ('escalated', 'Escalated')], default='to_be_followed', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='storeinspection',
            index=models.Index(fields=['batch', 'inspection_date', 'slot'], name='inspections_batch_i_373119_idx'),
        ),
        migrations.AddField(
            model_name='inspectionwifiweakpoint',
            name='store_inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi_weak_points', to='inspections.storeinspection', verbose_name='Store Inspection'),
        ),
        migrations.AddIndex(
            model_name='inspectionwifiweakpoint',
            index=models.Index(fields=['store_inspection', 'sort_index'], name='inspections_store_i_0858d7_idx'),
        ),
    ]
