# Generated by Django 5.2.8 on 2026-04-15 07:01

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_make_division_code_optional'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50, unique=True, verbose_name='Quotation Number')),
                ('quotation_date', models.DateField(default=datetime.date.today, verbose_name='Quotation Date')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('attn', models.CharField(blank=True, max_length=200, verbose_name='Attention')),
                ('tel', models.CharField(blank=True, max_length=20, verbose_name='Telephone')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('total_without_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Without Tax')),
                ('total_with_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total With Tax')),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Tax')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='companies.company', verbose_name='Customer')),
                ('customer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='customers.customerprofile', verbose_name='Customer Profile')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('invoice_pdf', 'Invoice PDF'), ('invoice_ofd', 'Invoice OFD'), ('invoice_xml', 'Invoice XML (Zipped)'), ('email_confirmation', 'Email Confirmation Screenshot')], max_length=30, verbose_name='Attachment Type')),
                ('file', models.FileField(upload_to='quotations/attachments/%Y/%m/', verbose_name='File')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotations.quotation', verbose_name='Quotation')),
            ],
            options={
                'verbose_name': 'Quotation Attachment',
                'verbose_name_plural': 'Quotation Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, verbose_name='Brand')),
                ('product_description', models.TextField(verbose_name='Product Description')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Model Number')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5, verbose_name='Tax Rate (%)')),
                ('price_without_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Price Without Tax')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tax Amount')),
                ('line_total_without_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Line Total')),
                ('line_total_with_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Line Total With Tax')),
                ('user_brand', models.CharField(blank=True, max_length=255, verbose_name='User Brand')),
                ('user_name', models.CharField(blank=True, max_length=200, verbose_name='User Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('product_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='products.productprice', verbose_name='Product Price')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation', verbose_name='Quotation')),
            ],
            options={
                'verbose_name': 'Quotation Item',
                'verbose_name_plural': 'Quotation Items',
                'ordering': ['id'],
            },
        ),
    ]
