# Generated by Django 5.2.8 on 2026-04-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='customer_profile',
        ),
    ]
