# Generated by Django 5.2.8 on 2026-04-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_remove_quotation_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='sent', max_length=20, verbose_name='Status'),
        ),
    ]
