# Generated by Django 5.2.8 on 2026-04-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_alter_quotation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='attn_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Attention Email'),
        ),
    ]
