# Generated by Django 5.2.8 on 2026-04-24 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_receivedemailmessage_rfq_confidence_and_more'),
        ('quotations', '0004_quotation_attn_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='requires_confirmation',
            field=models.BooleanField(default=False, verbose_name='Requires Confirmation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='source_email_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_quotations', to='accounts.receivedemailmessage', verbose_name='Source RFQ Email'),
        ),
    ]
