# Generated by Django 5.2.8 on 2026-04-29 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_serviceitem_alter_productprice_options_and_more'),
        ('quotations', '0005_quotation_requires_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='service_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='products.serviceitem', verbose_name='Service Item'),
        ),
    ]
