# Generated by Django 5.2.8 on 2026-04-16 03:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0006_asset_source_quotation'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(max_length=50, unique=True, verbose_name='Delivery Number')),
                ('delivery_date', models.DateField(default=datetime.date.today, verbose_name='Delivery Date')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='Receiver Name')),
                ('receiver_phone', models.CharField(max_length=20, verbose_name='Receiver Phone')),
                ('delivery_address', models.TextField(verbose_name='Delivery Address')),
                ('delivery_method', models.CharField(blank=True, max_length=100, verbose_name='Delivery Method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('prepared', 'Prepared'), ('dispatched', 'Dispatched'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='deliveries/signed/%Y/%m/', verbose_name='Signed Copy')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_orders', to='quotations.quotation', verbose_name='Source Quotation')),
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=255, verbose_name='Serial Number')),
                ('brand_name', models.CharField(blank=True, max_length=255, verbose_name='Brand')),
                ('product_description', models.TextField(blank=True, verbose_name='Product Description')),
                ('user_brand', models.CharField(blank=True, max_length=255, verbose_name='User Brand')),
                ('user_name', models.CharField(blank=True, max_length=200, verbose_name='User Name')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='assets.asset', verbose_name='Asset')),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.deliveryorder', verbose_name='Delivery Order')),
            ],
            options={
                'verbose_name': 'Delivery Item',
                'verbose_name_plural': 'Delivery Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['delivery_number'], name='deliveries__deliver_c0af10_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['status'], name='deliveries__status_5c03f6_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['delivery_date'], name='deliveries__deliver_16d33a_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliveryitem',
            constraint=models.UniqueConstraint(fields=('delivery_order', 'asset'), name='unique_asset_per_delivery_order'),
        ),
    ]
