# Generated by Django 5.2.8 on 2026-04-15 06:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0005_alter_assetmodel_model_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='PCS', help_text='Unit of measure (e.g., PCS, SET, KG)', max_length=50, verbose_name='Unit')),
                ('price_without_tax', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price Without Tax')),
                ('price_with_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price With Tax')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), help_text='Tax rate as percentage (e.g., 13.00 for 13%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Tax Rate (%)')),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the current active price', verbose_name='Current Price')),
                ('valid_from', models.DateField(blank=True, help_text='Date from which this price is valid', null=True, verbose_name='Valid From')),
                ('valid_until', models.DateField(blank=True, help_text='Date until which this price is valid', null=True, verbose_name='Valid Until')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='assets.assetbrand', verbose_name='Brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='assets.assetmodel', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'ordering': ['brand__name', 'model__name'],
                'unique_together': {('brand', 'model')},
            },
        ),
    ]
