# Generated by Django 5.2.8 on 2026-04-29 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_assetcategory_item_type'),
        ('products', '0002_productprice_history_and_current_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_group', models.CharField(blank=True, max_length=255, verbose_name='Service Group')),
                ('name', models.CharField(max_length=255, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('unit', models.CharField(default='JOB', max_length=50, verbose_name='Unit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Items',
                'ordering': ['service_group', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['service_item__name', 'brand__name', 'model__name', '-is_current', '-valid_from', '-updated_at'], 'verbose_name': 'Product Price', 'verbose_name_plural': 'Product Prices'},
        ),
        migrations.RemoveConstraint(
            model_name='productprice',
            name='uniq_current_product_price_per_model',
        ),
        migrations.AlterField(
            model_name='productprice',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='assets.assetbrand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='assets.assetmodel', verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='service_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='products.serviceitem', verbose_name='Service Item'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('model__isnull', False), ('service_item__isnull', True)), models.Q(('model__isnull', True), ('service_item__isnull', False)), _connector='OR'), name='productprice_single_catalog_target'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('model__isnull', False)), fields=('model',), name='uniq_current_product_price_per_model'),
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('service_item__isnull', False)), fields=('service_item',), name='uniq_current_product_price_per_service_item'),
        ),
    ]
