# Generated by Django 5.2.8 on 2026-05-11 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_assetcategory_item_type'),
        ('products', '0004_migrate_service_prices_to_service_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20, verbose_name='Request Type')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('catalog_type', models.CharField(choices=[('hardware', 'Hardware'), ('service', 'Service')], max_length=20, verbose_name='Catalog Type')),
                ('requested_service_group', models.CharField(blank=True, max_length=255, verbose_name='Requested Service Group')),
                ('requested_service_name', models.CharField(blank=True, max_length=255, verbose_name='Requested Service Name')),
                ('requested_service_unit', models.CharField(blank=True, max_length=50, verbose_name='Requested Service Unit')),
                ('current_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Current Snapshot')),
                ('proposed_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Proposed Snapshot')),
                ('request_notes', models.TextField(blank=True, verbose_name='Request Notes')),
                ('review_notes', models.TextField(blank=True, verbose_name='Review Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_product_price_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_product_price_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('target_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_approval_requests', to='assets.assetmodel', verbose_name='Target Hardware Model')),
                ('target_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='products.productprice', verbose_name='Target Product Price')),
                ('target_service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_approval_requests', to='products.serviceitem', verbose_name='Target Service Item')),
            ],
            options={
                'verbose_name': 'Product Price Approval Request',
                'verbose_name_plural': 'Product Price Approval Requests',
                'ordering': ['status', '-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='products_pr_status_e9a6fd_idx'), models.Index(fields=['catalog_type', 'status'], name='products_pr_catalog_e15e0b_idx'), models.Index(fields=['request_type', 'status'], name='products_pr_request_5c3135_idx'), models.Index(fields=['requested_by', '-created_at'], name='products_pr_request_9722bb_idx')],
            },
        ),
    ]
